### ISSUE TITLE
Load schemas from local variable by getting the raw $ref

### ISSUE THREAD

**Issue by angelsvirkov** [ajv-validator/ajv#1006]
**What version of Ajv you are you using?**

6.7.0

**What problem do you want to solve?**

I would like to get the initial value of any `$ref` which is not found (`MissingRef`). Thus, I would be able to load additional referenced schemas from a local variable / map. Currently, the `loadSchema()` method gets called with either a resolved URI or the `$ref` itself. Therefore, I would have to apply some conditional logic to infer the actual `$ref` which was missing in the first place, by parsing the URI and so on. I would like to be able to get the initial `$ref` directly in the `loadSchema()` method so that I can check whether the initial `$ref` is already available in the local record of schemas and load it from there or otherwise load it from any upstream host. 

**What do you think is the correct solution to problem?**

I think one of the solutions is to pass a second parameter, which holds the initial missing `$ref`, to the `loadSchema()` method. 

- I can't think of any other solution which makes this possible in the package itself.
- I also tried the `ajv.addSchema()` to add any local schemas, but then the `loadSchema()` is still getting called.

**Will you be able to implement it?**

Yes, the `MissingRefError` needs to have another property. Something like `initialRef`. Eventually, the `loadSchema()` method has to be called with two parameters - the resolved URI and the `initialRef`. This could easily be done inside `loadMissingSchema()` of `async.js`

**Comment by epoberezkin** [comment]
I think you may be mixing some concepts. loadSchema is always passed schema ID. $ref is not a schema ID, in general case, it is a relative URI that should be resolved using current schema ID as the base URI. Therefore the SAME schema can be referenced using full URI and relative URI - and loadSchema is always passed full resolved URI because in both cases it should provide the same schema object.

Whether this schema is available in memory or it should be downloaded from any remote resource or from the database or from a local file is completely irrelevant here - the spec explicitly says that schema ID being URI does NOT mean that this schema is available at this URI.

The role of loadSchema function is to provide the mapping from URI to the schema objects - where these objects are stored is an application concern, not something that Ajv should be aware of.

**Comment by angelsvirkov** [comment]
Thanks for the fast answer. I get a better idea for the `loadSchema()` method now. Nevertheless, I am asking for a way to get the value of any missing `$ref`. This is currently impossible if I don't apply some reverse engineering on the `uri` passed inside `loadSchema()`. Maybe I did not communicate well enough in the first place. I don't want to make Ajv aware of where the schema comes from. I just need a way to get the value of a missing `$ref` so that I can decide in my application where I get the actual schema object from.

So, I believe it would be valuable for Ajv itself to have a way to provide a not-found `$ref` or all not-found `$ref`s

**Comment by epoberezkin** [comment]
For example, you have a schema:

```json
{
  "$id": "https://example.com",
  "properties": {
    "a": {"$ref": "/schema.json"},
    "b": {"$ref": "https://example.com/schema.json"},
  }
}
```

Both refs mean exactly the same schema with the same URI and you should not make any logic depend on whether you have full or relative URI in $ref. So in both cases loadSchema would be called with "https://example.com/schema.json".

Refs should not be interpreted as is, outside of the context of the schema where they are used, so I think it can only cause mistakes if they are passed without being resolved with the base URI (schema $id).

**Comment by epoberezkin** [comment]
Closing it, as $ref's should not be interpreted outside of the schema where they are used.
