### ISSUE TITLE
Remove case-sensitiveness of type

### ISSUE THREAD

**Issue by amir-rahnama** [ajv-validator/ajv#107]
It took me ages to find that the schema type: 'Object' is throwing the exception:

`UncaughtException Error: schema is invalid:data.type should be equal to one of values, data.type should be array, data.type should match some schema in anyOf`

Can it be removed please?

**Comment by epoberezkin** [comment]
Sorry, but there is the standard to follow... It would also have a negative performance impact. The error was pointing to the offending property of the schema - top level `type`.

If you like you can turn off schema validation but then you'll have harder time debugging false positives because instead of throwing an exception during schema validation/compilation it would quietly ignore `type` keyword during data validation.
