### ISSUE TITLE
Returning the detected entity

### ISSUE THREAD

**Issue by NathanHazout** [ajv-validator/ajv#1152]
I'm not yet using ajv, I'm looking around at different libraries.

Let's say I have a complex schema, and I am sending data for validation.  
Is there a way, assuming the validation returned true, to know what path in the schema returned a valid answer?

For example, my schema accepts both WidgetA and WidgetB, I send some widget for validation and as an output I want to know which type of widget I have detected.

**Comment by sambauers** [comment]
Can't you just read some distinctive value from the JSON you are validating to find out?

Or you could setup two schemas, one for each widget, and one will pass and one will fail. You can tell which widget you are validating by the result of the two tests combined.

**Comment by NathanHazout** [comment]
Right, those are 2 workarounds I also thought about. I was hoping there is something built-in either the schema specs or the implementation that will help me do this.
(FYI, I also asked in slack, attaching answer here).

I'm trying to make the module I'm building generic, meaning not hardcoding any type name in my code.

<img width="732" alt="Screen Shot 2020-01-22 at 10 49 12" src="https://user-images.githubusercontent.com/329834/72879256-2f8b2380-3d05-11ea-8e6e-97e7bb99d6f9.png">

**Comment by epoberezkin** [comment]
JSON schema is defined as a collection of (mostly ) independent restrictions on the data - it may look in some cases as a declaration of what the data must look like, but in general case it is not. 

Because of that it’s not possible in general case to identify a part of the schema that the data has passed against - it has passed (or not) against the whole schema. There are some subsets of all JSON Schemas for which this question can be answered, but not for all, so it’s not in scope.
