### ISSUE TITLE
Can't resolve reference 

### ISSUE THREAD

**Issue by akopchinskiy** [ajv-validator/ajv#1188]
AJV couldn't resolve reference of sub schema in one of two absolutely identical schemas.

```ts
        const ajv = new Ajv({
            validateSchema: true,
            schemaId: '$id',
            allErrors: true
        });

        ajv.addSchema([
            require(path.resolve(__dirname, '../../design/schemas/server/v3/base.json')),
            require(path.resolve(__dirname, '../../design/schemas/server/v3/person.json')),
            require(path.resolve(__dirname, '../../design/schemas/server/v3/order.json'))
        ]);
```

order.json
```json
{
   ...
    "allOf": [
        {
            "$ref": "base.json"
        },
        {
  ...
```
person.json
```json
{
    ...
    "allOf": [
        {
            "$ref": "base.json"
        },
        {
  ...
```
Schemas are in the same folder.

```ts
    // At the same file:
    valid = ajv.validate('order_v3', item);  // true
    ...
    valid = ajv.validate('person_v3', item);  // can't resolve reference base.json from id person_v3#
```

How's this possible?

**Details:**
node v13.2.0
ajv v6.12.0

**Comment by epoberezkin** [comment]
It is difficult to say what is wrong without full code sample, but file location is completely irrelevant here. What is important is $id keyword in the root of the schema - it should be "base.json" for these $refs to work (or it can be full qualified ID provided $id of person.json has the same path). So it can be that order.json $id has the same path and person.json $id has different path (I mean only URI path, not file location). Or it can be that $ref in order is in the unused part of the schema because of some mistake, and that's why it does not fail...

**Comment by epoberezkin** [comment]
please submit additional information if it's still the problem - closing for now.
