### ISSUE TITLE
Can use in global function that will be run concurrently by billons?

### ISSUE THREAD

**Issue by chaoticvibe** [ajv-validator/ajv#1197]
I just want know, if i create schema with Ajv.addSchema(), compile, and put it on a global object lik, global.MySchemas['TheSchemaName'], with global.MySchemas['TheSchemaName'] = Ajv.getSchema(); We can assume that we save more memory usage, than using Ajv.getSchema(); everytime that we will use it? So, we can believe that global.MySchemas['TheSchemaName'] will be used lot concurrently, so...
function validateMiddleware(){
var validate = global.MySchemas['TheSchemaName']; 
var valid =  validate(JsonBody);
if(valid){
//All valid, do that stuff
}else{
//Work with errors
validate.errors;
}
}
The above code results never will be affected by the anotther execuction concurrently of the same global.MySchemas['TheSchemaName'] ?

Sorry for any mistakes, i'm new in Github and new with Ajv.

**Comment by epoberezkin** [comment]
> We can assume that we save more memory usage, than using Ajv.getSchema(); everytime that we will use it?

Not that much of a difference, as getSchema only compiles the schema the first time, on the subsequent calls it simply retrieves already compiled schema from ajv instance. While it is no harm making all the schemas you need globally available, it is probably a better pattern to either make ajv instance globally available (or some wrapper - see below) and to access schema(s) via it.

> The above code results never will be affected by the anotther execuction concurrently of the same global.MySchemas['TheSchemaName'] ?

Yes, it is safe because JavaScript is single threaded - there are no concurrent threads that can have shared access to the same memory. While subsequent calls to `validate` will overwrite `validate.errors`, they are not overwritten in place - it creates a new array every time. So if you copy the errors array reference to another variable, it won't be affected by the subsequent calls (even if you don't process errors synchronously). 

It is quite common to create a wrapper in the application that provides a handle to access ajv and all schemas with Api that you find comfortable yo use - most frameworks that depend on ajv do it one way or another, so ajv is used directly only in one module.

Hope it helps.
