### ISSUE TITLE
inlineRefs: true with useDefaults: true and default inside $ref assigns default inside composite keyword (instead of ignoring it)

### ISSUE THREAD

**Issue by akalsi87** [ajv-validator/ajv#1272]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

I'm using 6.12.4

**Your code**

See [runkit ajv-issue](https://runkit.com/akalsi87/5f53b89aa5c9e4001a20547d).

**Validation result, data AFTER validation, error messages**

```
TypeError: Validation error for type 'Config': [
  {
    "keyword": "required",
    "dataPath": ".publicAddress.ip",
    "schemaPath": "IpEndpoint#/definitions/IpEndpoint/required",
    "params": {
      "missingProperty": "host"
    },
    "message": "should have required property 'host'"
  },
  {
    "keyword": "required",
    "dataPath": ".publicAddress",
    "schemaPath": "#/oneOf/1/required",
    "params": {
      "missingProperty": "unix"
    },
    "message": "should have required property 'unix'"
  },
  {
    "keyword": "oneOf",
    "dataPath": ".publicAddress",
    "schemaPath": "#/oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "should match exactly one schema in oneOf"
  }
]
```

**What results did you expect?**

Equivalent output with inlineRefs = true and inlineRefs = false.

**Are you going to resolve the issue?**

Can do with help. Relatively new to JavaScript and AJV and JSON Schemas. 😄

**Comment by epoberezkin** [comment]
@akalsi87 thank you. A smaller example showing the issue would help understanding/investigating it. Could you try to identify what should be added to a working example for it to stop working:

https://runkit.com/esp/5f5723082f38cd001a39a232

Or try removing all elements from your schema and applciation to the point when removing anything prevents the issue from appearing - it should be possible to reproduce with a much smaller schema unrelated to your application domain.

**Comment by epoberezkin** [comment]
Also, it would help removing registry from the example - it is obfuscating what is the actual schema being processed.

**Comment by akalsi87** [comment]
Sure @epoberezkin . Please see [the simplified example](https://runkit.com/akalsi87/5f57731e08dc240021f64783).

When `inlineRefs === true`, the output is `[true, false]`.
When `inlineRefs === false`, the output is `[true, true]`.

**Comment by epoberezkin** [comment]
@akalsi87 The problem here is the combination of $ref and oneOf keyword - defaults should not be assigned inside oneOf - see readme. If you take the schema out of oneOf, the default is assigned independent of inlineRefs - see modified example https://runkit.com/esp/5f5e02d7c06de500138b47e8.

It would be the same with any other "composite" keyword, i.e. the keyword with subschemas that are combined in any other way than simple boolean AND

So the problem here is the opposite, defaults should NOT be assigned in both cases, but when $ref is not inlined Ajv does not take into account that the schema is inside of "composite" keyword (the logic was mostly introduced for error reporting, but when subschema is compiled into a separate function, while it is not needed for error reporting it is still needed for defaults...).

Given that inlineRef: true is default, so for most users it's the documented behaviour, I will address it in v7, one way or another - either to add support for defaults inside oneOf or to make the behaviour consistent (by passing additional parameter to validation function that it is called inside "composite" keyword and prevent assigning defaults).

**Comment by akalsi87** [comment]
Thanks @epoberezkin . This makes sense. Would you say that for composability (and maybe code-reuse JIT reasons) it is better to use `inlineRefs: false` than `inlineRefs: true`?

My 2c: the current behaviour with `inlineRefs === false` meets my expectations as a user. It is surprising if with `inlineRefs === false` the same validation function would behave differently.

**Comment by epoberezkin** [comment]
Currently defaults in oneOf are affected by the order of branches (they same data can be valid or invalid if you change the order), so they should not be used in allOf/ oneOf/anyOf/not.

Normally they would be ignored (and throw exception with strictDefaults) but using $ref with inlineRefs: false allows to circumvent this limitation.

You need to refactor the schema is some other way, e.g. with if/then/else.

**Comment by akalsi87** [comment]
I appreciate your follow-up responses. :)

> Currently defaults in oneOf are affected by the order of branches (they same data can be valid or invalid if you change the order), so they should not be used in allOf/ oneOf/anyOf/not.

Understood. I think this is not a problem if there is a wrapping property for the underlying type disambiguating the use. If however, the same properties can be in different branches of the oneOf, it can be ambiguous. It seems that there are ways to do this correctly and there are foot guns. Does it make sense to enable sensible use while erroring on erroneous constructs at JSON schema parse time?

**Comment by epoberezkin** [comment]
Yes, there are some scenarios when it would work ok, but there are too many cases to analyse programmatically. With draft 2019-09 support it would be much easier together with unevaluatedProperties keyword support.

**Comment by epoberezkin** [comment]
It's actually the same as https://github.com/ajv-validator/ajv/issues/337

**Comment by epoberezkin** [comment]
close in favour of #337
