### ISSUE TITLE
if/then validation not applied when value requires coercion.

### ISSUE THREAD

**Issue by willfarrell** [ajv-validator/ajv#1372]
Sorry, for another one so quickly.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v7.0.2

**Ajv options object**
```javascript
{
  strict: false,
  coerceTypes: true,
  allErrors: true
}
```

**JSON Schema**
```json
{
  type: 'object',
  properties: {
    value: {
      type:'number'
    }
  },
  allOf:[{
    "if": {
      "required": ["value"]
    },
    "then": {
      "properties": {
        "value": {
          "minimum": 0,
          "maximum": 14
        }
      },
      "required": ["value"]
    }
  }]
}
```

**Sample data**

```json
{
  'value': '-1'
}
```

**Your code**

```javascript
const Ajv = require('ajv').default

const ajv = new Ajv({
  strict: false,
  coerceTypes: true,
  allErrors: true
})
let validateTest = ajv.compile({
  type: 'object',
  properties: {
    value: {
      type:'number',
      minimum:0
    }
  }
})
// Test 1
validateTest({
  'value': '-101'
})
console.log('expected', validateTest.errors) // Error on minimum

validateTest = ajv.compile({
  type: 'object',
  properties: {
    value: {
      type:'number'
    }
  },
  allOf:[{
    "if": {
      "required": ["value"]
    },
    "then": {
      "properties": {
        "value": {
          "minimum": 0,
          "maximum": 14
        }
      },
      "required": ["value"]
    }
  }]
})

// Test 2
validateTest({
  'value': -1
})
console.log('expected', validateTest.errors) // Error on minimum & if

// Test 3
validateTest({
  'value': '-1'
})
console.log('unexpected', validateTest.errors)  // null, expect same as test 2
```

**What results did you expect?**
From the above code I expect test 3 to have the same validation errors as test 2. This also applies when using `anyOf` and `oneOf`. Test 1 does coerce and validate properly when not using conditional logic. This does run as expected with ajv v6.

**Comment by epoberezkin** [comment]
Thank you.

v7 had to have a different order of keyword validation to accommodate for unevaluatedProperties - in v6 the keywords that apply to all types (allOf etc.) were validated after keywords that apply to specific types (properties etc.), but in v7 it is the other way around - keywords that apply to all types are validated first (to be able to track which properties/items are validated - it is only done in draft-2019-09 Ajv class, but the order is the same in both Ajv classes). For pure validation it does not matter, but when validation changes the data the order is important.

The order was never documented or guaranteed, it was always better to define the required order explicitly with allOf keyword, because without it whether it works or not is accidental...

The required schema change in this case is to make the order explicit by putting "properties" inside the first item in "allOf" (otherwise there would be no need to group if/then inside allOf - probably reads better this way anyway):

https://runkit.com/esp/5fe99f56b77aad001ba15c0b

**Comment by epoberezkin** [comment]
I now added the comment to the release notes about it.

**Comment by willfarrell** [comment]
Thanks for the detailed explanation and the interesting workaround to resolve it. I would have never thought to move the properties inside the `allOf` without the implementation history you provided.

Thanks again for the quick assistance, much appreciated.

**Comment by epoberezkin** [comment]
You are welcome.

Arguably, this is not a workaround, but the correct usage ;) If your schema mutates the data in the process of validation then defining explicit order is the only way to get predictable results.

The problem with "JSON as code" approach is that properties are unordered; only for arrays the order is defined... JSON Schema itself is defined as declarative DSL and the order is irrelevant there, but data mutations make it into imperative DSL...

I am actually thinking - maybe strict mode can be extended to warn about the situations when the schema can mutate the data (from the combination of used keywords and options) and the iteration order is not explicitly defined... Although it is non-trivial to determine these cases.
