### ISSUE TITLE
Improve discoverability in docs

### ISSUE THREAD

**Issue by alesmenzel** [ajv-validator/ajv#1406]
I am really unhappy with how the docs are hiding the validation keywords.
Now you need to search the whole docs to find them.

**Repro:**
1) You need to scroll 1/3 of the [ajv homepage](https://ajv.js.org/)
2) Find it in the list of content
```
Data validation
Validation basics: **JSON Schema keywords**, annotations, formats
```
3) Search another list of contents
```
Data validation
  JSON Schema draft-2019-09
  Validation basics
     **JSON Schema validation keywords**
```
4) Search in the text and find a link for the keywords
```
Ajv supports all validation keywords from draft-07 of JSON Schema standard - see **JSON Schema validation keywords** for more details.
```
5) Scroll down to a list of keywords
6) Click on a keyword
🎉 You have finally found keywords for a type ... 

So after all I have to click "JSON Schema keywords" 3x before I finally get to that page 😞

**Comment by aymenha** [comment]
People in my team were confused, as some couldn't find the docs for keywords. Last time I checked, this was easily accessible through the navbar or the main page, if I'm not mistaken.

This is the page you're looking for (in case any lost soul stumbles upon this Issue)
Docs: https://ajv.js.org/docs/json-schema.html

**Comment by epoberezkin** [comment]
thanks for the feedback. The new website is coming soon and so does support of JSON Type Definition - the RFC that is alternative to JSON Schema standard. So the docs will be more discoverable - I'll keep it open for now.

Whether Ajv docs should be the source of information on JSON Schema spec is a question to think about - I am considering simply linking to the source (JSON Schema org website) rather than having info on keywords as part of Ajv docs...

**Comment by epoberezkin** [comment]
The new website is still work in progress, but docs are more discoverable now with better navigation and search: https://ajv.js.org
