### ISSUE TITLE
Incompatible android browser (4.0)

### ISSUE THREAD

**Issue by ewanjuki** [ajv-validator/ajv#143]
An "Unexpected SyntaxError: Unexpected strict mode reserved word" is thrown for the enum property in the exported object in line 254 ajv.bundle.js. This occurs in strict mode for this browsers. What might be the issue?

I'm using React, Browserify and Gulp.

**Comment by epoberezkin** [comment]
It seems like the browser doesn't like "enum" being used as the property name without quotes, because enum is a reserved word... ES5 allows unquoted reserved words as property names, but apparently Android 4 doesn't fully support ES5.

Please try quoting the properties in this object in the code to see if it works. I think something else may still be not working.

**Comment by epoberezkin** [comment]
On Android 4 `typeof` of any RegExp is "function" instead of "object".

**Comment by epoberezkin** [comment]
@wanjuki10 fixed in 4.0.1, please let me know if something doesn't work.

**Comment by epoberezkin** [comment]
please reopen if you notice some issue.
