### ISSUE TITLE
Option to show all errors in structure (down below)

### ISSUE THREAD

**Issue by studio404pl** [ajv-validator/ajv#145]
Is there any possibility to add option to validation to show all errors down below the current empty path?

for example path 
`.drawer.shelf`

and `shelf` is declared as object where we have required params to fill like `car`, `ball`, `book` but during inserting json object `shelf` is empty.. currently i am getting only information that `shelf` is required and missing. Is there any possibility to get also error related to children elements `car`, `ball`, `book`?

**Comment by epoberezkin** [comment]
The JSON-schema spec says that the the schema in properties should be applied to `.shelf` only if the property `.shelf` is present.

You could add `default: {}` in the schema at the levels of `.drawer` and `.drawer.shelf` and use `useDefaults: true` option:

``` javascript
{
  properties: {
    drawer: {
      default: {},
      properties: {
        shelf: {
          default: {},
          required: ['car', 'ball', 'book']
        }
      }
    }
  }
}
```

In this case you will get errors for children but you won't get an error for missing `.drawer` or `.shelf`, because the default will be used. Not sure if it's better for you.

The alternative is to process the returned errors and add the messages you need...

**Comment by epoberezkin** [comment]
Please let me know if you think some improvement is possible here.
