### ISSUE TITLE
Change validate, compile and getSchema signatures in JTD instance

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#1453]
I am not sure if it is possible to have different method signatures in the subclasses without having them in a superclass. If it were possible then core class would have no type-guard methods and Ajv class and JTD class would respectively use JSONSchemaType and JTDSchemaType.

It is possible of course by defining methods in the subclasses and calling a super-class method, but it creates an additional function call only to change type signature.

A better alternative would be to simply add type signatures to the core class to support JTDSchemaType in addition to JSONSchemaType.

@erikbrinkman - any thoughts?

**Comment by erikbrinkman** [comment]
I'm not quite sure exactly what you're asking, but that's mostly because I'm not super familiar with the structure of ajv. I don't think I know a whole lot about how the compiling code works or is structured. If JTD doesn't support all of the fancy whistles of JSONSchema (e.g. asynchronous loading, etc.) then then yeah, a subclass where you just redefine them is probably easiest.

If you think that will create overhead or be unworkable, then I think you should be able to put it in the ajv class itself.  The question to me then becomes, do you want / plan to include other schemas, e.g. for the foreseeable future will ajv only validate two types of schemas, or do you think it's likely to increase? One way that could be added relatively simply to the class would be something like [this](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAsAFDIXIBWYAJgPwBcyARttgDYRwgDcZAXzJkwAT3QoAUgBUAIgGUEACwgBbONPEoAvMhABXVS2gitySfNQA5RSvWaJyXXjBRQAc2GkA9N+RXUaQBRZFFsfWQlOAA3FDBsVhQEOCgIGH0OSOgIABpkMBVkWjS4DLB8s2ACNk5uEGQAH2R9EGKYUAhaPLwE130UeA48FB5aZta0jrG4DkyIAA9IVuRgMFNHWTSnNEwcfABtACIaWkOAXS8EDjg8AgBBKmiAHgwwAgWl2gJXvbwAPiIZEoyGwmDwzFeeCBlAQuBcUH0CHiUAAFKC3hCwQBKQHkYGUApVAB06IIulJ-DxFCEpGhFFhqnQwC4KLwyjUcGYg2GyA+EFa3zBRxO52Q9HMlhs7PsZmYMgU0o0WixzGi2GAYxItKpyBpNLIsPw5RO2xAEAA7sgHtEUYRqHRmH0RgQnbqsZSxI55QAFFJwVTbX1Qf0QSBQPBPFGeiDYGD22hYo4Mplcc5-fYABgupENLmoPXqujNluttoE7vWUklQf9gb9qlD0AjUa0sfzuETh2TzIgacz2bIQA). It basically parameterizes the AJV class on it's options, allowing them to be more specific, it then uses that specificity to decide the parameter types. If you expected more schemas you could do something like make a mapping `{ json: JSONSchemaType, jtd: JTDSchemaType }` and parametrize on the keyof that type, then doing a lookup instead of a bunch of ternary operators.

Do those ideas make sense? Is that what you're going for?

**Comment by epoberezkin** [comment]
> structure of ajv

there is a core class that is not used by users (it has no validation keywords) but it has all logic - compile method is there. The subclasses add different keywords but do not change most methods (compile is the same for both JSON Schema Ajv subclass and for JTD Ajv subclass).

So my question was whether it is possible to change the type signature in the subclass without redefining the method (something typescript specific).

> do you want / plan to include other schemas

very unlikely.

I am focussing on extending JTD support, currently adding compilation of parsers and serialisers - they are much faster (2-10 times) than JSON.parse/stringify, because they fail fast when parsing and do not need to traverse the serialised data when the structure is known (I think fastify uses similar approach with JSON Schema, but it is only possible for subset of JSON Schema). So in the spirit of "parse don't validate" it kind of makes validation itself not so necessary.

> parameterizes the AJV class on it's options

It would make it a bit bulky I think... I'll probably have to make type signatures in core class accept the whole bunch of options - for JSONSchemaType, for JTDSchemaType and for your new JTDDataType too - which is not a problem really...

**Comment by erikbrinkman** [comment]
Then do you just mean doing something like [this](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCBWA3AQpAptA3gKGtYA9gLYAOAliGgBQTAAWaRYAXNAK4B2A1hwQO4cAlKyoEARvFace-IdAC8APmhiCBSmA5ZceaIgJkAJtFoMmAbh14ATmgAuba1qqCFygGZgQENJbwBfbEDsOwBPEgwAKQBlAHkAOWj6RjAAHgAVZXloLjRQgndodOg0AA87NA5DGAg7azIOAHNoAH4saDCI1gAieAgCDm7of2hWDjRENGsQ8Kj0gBEkszTMhRy8gqKS8srqkzqG5rbMDtme+DtDIZGxiansbFBIGARESP6tHDxCUgo0DMUNGSTFYMQSSxSAOE0FEEik3F4AlcSmg4ng0DIMGKX10+iMJmBYD8ulsDicMLR8JkSNYaIxWLc7TxxjR5mgpMcWk83l8w2JgWCTygcCQkUu2m+xHIlABQOWoIWEKYUJElPYCNkyOUdMxWxxeGZBOWxJs9k5FLh6upQlpEnpWxRJ0NrPZZvJ3J8bP8-KCQAP)? In general subclasses should be able to specialize a signature but not generalize it.

**Comment by epoberezkin** [comment]
Well, in this case I’ll have to call core methods from both - was hoping to avoid it - only defining overloads without implementations in subclasses. Looks like it’s not possible... Specializing type signatures in subclasses is what I need but I’d have to call super.compile for the sake of type signatures only - implementation is the same... that’s ok - no problem.

**Comment by erikbrinkman** [comment]
I think I'm probably missing something you're trying to achieve, and I'm not sure how best to resolve my lack of understanding. I'm happy to spend some more time brainstorming ideas if you'd rather try and find an alternative.

My current guess is right now you have something like:
```
class Ajv {
   compile<T>(schema: JSONSchemaType<T>): (obj: unknown) => obj is T
}
```
and you want to be able to do something like:
```
class AjvJTD extends Ajv {
   compile<T>(schema: JTDSchemaType<T>): (obj: unknown) => obj is T
}
```
That definitely isn't possible, you would need to have the common base class. However, if you really do want to avoid minimal changes, the style I described at the beginning should work. Basically, just have a boolean type flag for the jtd option. If the flag is specifically set to true, then use jtd signatures. You will have to include all the signatures in the original definition, but it avoids a restructuring, and if you only plan to support JTD it shouldn't be an issue.

**Comment by epoberezkin** [comment]
Added types to signatures
