### ISSUE TITLE
JSONSchemaType support for Record

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv#1491]
**Version**
v8

**Problem**
Currently JSONSchemaType does not support types like `Record<string, T | undefined>` (or `{[K in string]?: T}`).

**Solution**

For the type for example:

```typescript
type MyRecord = Record<string, number | undefined>
```

JSONSchema should be:

```typescript
const myRecordSchema: JSONSchemaType<MyRecord> = {
  type: "object"
  additionalProperty: {type: "number"}
}
```

It should also allow `propertyName` keyword.

Possibly, below should also type check (although it can be expressed with `properties` but it would be more verbose:

```typescript
type MyEnumRecord = Record<"a" | "b" | "c" | "d", number | undefined>

const myEnumRecordSchema: JSONSchemaType<MyEnumRecord> = {
  type: "object"
  propertyNames: {enum: ["a", "b", "c", "d"]}, // it won't check for completeness
  additionalProperty: {type: "number"}
}
```

(Although it would require properly supporting enum, which currently is not type checked at all)

**Comment by erikbrinkman** [comment]
Is there a reason why the latter case shouldn't be:
```
const myEnumRecordSchema: JSONSchemaType<MyEnumRecord> = {
  type: "object"
  properties: {
    a: { type: "number" },
    b: { type: "number" },
    c: { type: "number" },
    d: { type: "number" }
  },
  required: [],
}
```

**Comment by epoberezkin** [comment]
I think both should be accepted. The record syntax is needed if the type is just `string` (in which case you don't even need propertyNames, but it should be allowed). It's an equivalent of `values` in JTD - JSON Schema doesn't have a separate syntax for it.

**Comment by erikbrinkman** [comment]
As I think about this, it seems like the solution is that when we hit the Record branch, we can go the standard way where we just specify everything, or we can go an alternate route, and the alternate route looks like:
```
{
  type: "object",
  propertyNames?: {enum: (keyof T)[]},
  additionalProperty: JSONSchemaType<Omit<T[string], undefined>>,
  ... // other record properties
}
```
does that basically capture what you're suggesting?

**Comment by epoberezkin** [comment]
Yes, in general.

propertyNames should allow not only enum - enum only makes sense if they type is string union.

It should also allow format, pattern and any other keyword for strings...

The thing with JSON Schema is that we can't align it with the type as strongly as with JTD - JSON Schema can define a subset of what you can define with typescript types, so this type should allow for these.

**Comment by erikbrinkman** [comment]
I went back and looked at this more, and it looks like this is kind of supported, in that the schema will check as it is now. It just doesn't verify that you specified they keys of the object. It's possible to make it more strict, but since I don't actively use this, I'm curious as to how strict you want to make it.

The relevant lines are here:

https://github.com/ajv-validator/ajv/blob/b5642ea8655c3922de7f2403cc99d668871d35fb/lib/types/json-schema.ts#L93-L101

What I think makes the most sense is to split the properties out so it looks more like
```
{
  type:  JSONType<"object", _partial>
  // common properties
} & ({
  // general object properties
} | {
  // record specific properties
})
```

If nothing is removed or changed from common properties to general object properties, then this will be irrelevant as everything will type check. My first thought is to take `propertyNames` out so these would look something like this:
```
... & ({
        required: _partial extends true ? Readonly<(keyof T)[]> : Readonly<RequiredMembers<T>[]>
        additionalProperties?: boolean | JSONSchemaType<T[string]>
        unevaluatedProperties?: boolean | JSONSchemaType<T[string]>
        properties?: _partial extends true ? Partial<PropertiesSchema<T>> : PropertiesSchema<T>
        patternProperties?: {[Pattern in string]?: JSONSchemaType<T[string]>}
        dependencies?: {[K in keyof T]?: Readonly<(keyof T)[]> | PartialSchema<T>}
        dependentRequired?: {[K in keyof T]?: Readonly<(keyof T)[]>}
        dependentSchemas?: {[K in keyof T]?: PartialSchema<T>}
} | {
        additionalProperties?: JSONSchemaType<T[string]>
        patternProperties?: {[Pattern in string]?: JSONSchemaType<T[string]>}
        propertyNames: JSONSchemaType<string> | JSONSchemaType<keyof T>
})
```

although I'm not sure about dependencies. This would make propertyNames exclusive from `properties`, `required`, and `additionalProperties: bool`.

I'm asking so many questions, because this idea still rests largely in your head, and because if the complexity of JSONSchema, this type is not going to capture everything, so it becomes a design of what will be the most helpful to guide most usages to a correct type, without breaking anything that's also valid. I think you ultimately have more context for that than me.

**Comment by erikbrinkman** [comment]
@epoberezkin ping to get your feedback on what you had in mind

**Comment by epoberezkin** [comment]
> this is kind of supported

It does indeed allow for propertyNames, but it does not type check the example I put in the ticket.

The problem is not propertyNames, but additionalProperties.

So for the example:

```typescript
type MyRecord = Record<string, number | undefined>
// or type MyRecord = {[K in string]?: number}

const myRecordSchema: JSONSchemaType<MyRecord> = {
  type: "object",
  additionalProperty: { type: "number" },
}
```

The error is:

```
error TS2322: Type '{ type: "object"; additionalProperty: { type: string; }; }' is not assignable to type 'JSONSchemaType<MyRecord, false>'.
  Type '{ type: "object"; additionalProperty: { type: string; }; }' is not assignable to type '{ type: "object"; required: readonly never[]; additionalProperties?: boolean | JSONSchemaType<number | undefined, false> | undefined; unevaluatedProperties?: boolean | JSONSchemaType<...> | undefined; ... 7 more ...; maxProperties?: number | undefined; } & { ...; } & { ...; }'.
    Property 'required' is missing in type '{ type: "object"; additionalProperty: { type: string; }; }' but required in type '{ type: "object"; required: readonly never[]; additionalProperties?: boolean | JSONSchemaType<number | undefined, false> | undefined; unevaluatedProperties?: boolean | JSONSchemaType<...> | undefined; ... 7 more ...; maxProperties?: number | undefined; }'.
```

**Comment by erikbrinkman** [comment]
I see, I didn't understand that you were talking about an existing error. That being said though, the problem isn't that record isn't supported, it's that you didn't specify `required`.

```
const myRecordSchema: JSONSchemaType<MyRecord> = {
  type: "object",
  required: [],
  additionalProperties: { type: "number" },
}
```
typechecks fine, and seems like what you want.

**Comment by epoberezkin** [comment]
Right, indeed :)

That does solve the problem with a simple record, not very intuitively, and the record with enum type works if you add type string:

```typescript
type MyEnumRecord = Record<"a" | "b" | "c" | "d", number | undefined>

const myEnumRecordSchema: JSONSchemaType<MyEnumRecord> = {
  type: "object",
  propertyNames: {type: "string", enum: ["a", "b", "c", "d"]},
  additionalProperty: { type: "number" },
  required: [],
}
```

So it does work kind of ok indeed, but maybe to make it less counterintuitive we could:

1. Make "required" only required in cases when there are some required properties (which is not the case with records, but equally trips people up on objects with all optional properties).
2. Make `type: "string"` optional in propertyNames (it can only be string there). This is definitely a less important problem.

I guess, a general problem is also error messaging that is difficult to parse even for me, but typescript seems to offer no way to control it as some other languages with advanced types...

So, now that we got to the root :), it's probably worth to just close this issue and maybe create a separate one for 1? The second can be ignored I think, it's much less important.

**Comment by epoberezkin** [comment]
Closing it - please re-open if you think there's anything left here to do.

**Comment by erikbrinkman** [comment]
A few points:
1. Typescript errors aren't great. I agree. Unfortunately there's not a great way to customize them. There are some proposals of making a `never` style type with custom errors so you can better indicate what the problem is.
2. The way `JSONSchemaType` is implemented, all of these extra parameters are partial, so they can exist or not, but there's no guarantee that you fully specify the type, which is probably fine.
3. For your (2), it's currently `propertyNames?: JSONSchemaType<string>` so you could instead make it `Omit< JSONSchemaType<string>, "type"> & { type?: "string" }`. Which would just make type optional. Note that current property names does no validation, so you can specify an enum, but you can also put whatever you want in the enum.
4. For your (1), are you just thinking that `required` should be optional when `RequiredMembers` is empty

https://github.com/ajv-validator/ajv/blob/8762e6f8b17c4e61f3d47db502b19e99f4582724/lib/types/json-schema.ts#L138-L140

I agree that you could open new issues, but I think both of these are potentially pretty simple.
