### ISSUE TITLE
$ref vs inlining schema/definition object

### ISSUE THREAD

**Issue by Gameghostify** [ajv-validator/ajv#1608]
Maybe I'm missing something, but why should one use `$ref` when working in a JS-oriented environment?

For example, if I have partials/definitions that all validate one field of a user account:

```js
// src/user.js

export const usernameSchema = {
	type: "string",
	minLength: 5,
	maxLength: 100,
	pattern: "^[a-zA-Z]{5,100}$"
};

export const passwordSchema = {
    type: "string",
    minLength: 12
};
```

```js
// src/form.js

import { usernameSchema, passwordSchema } from "./form.js";

const registrationFormSchema = {
	type: "object",
	required: ["username", "password"],
	properties: { username: usernameSchema, password: passwordSchema } // import instead of { $ref: "..." }
};
```

\- Is it a bad practice to reuse these by importing them in other JS modules and then inlining them directly?
(Instead of putting them in a `"definitions"` and then using `"$ref"` to reference them)

I assume doing something like this would cause compilation "bloat" because the same code is generated multiple times. Same as the `inlineRefs` option.

**Comment by epoberezkin** [comment]
> Maybe I'm missing something, but why should one use $ref when working in a JS-oriented environment?

Yes, you absolutely can, I actually do it with JTD schemas when I need the same fragment across several schemas (and I don't want them all as parts of one schema). Performance-wise it is more efficient to have inlined fragments, size-wise it is more efficient to have $ref (and have inlineRef: false).

> Is it a bad practice to reuse these by importing them in other JS modules and then inlining them directly?
(Instead of putting them in a "definitions" and then using "$ref" to reference them)

If you only need it in JS then the only difference is as above. If you need other platforms, $refs are supported across multiple languages as part of the spec.

**Comment by Gameghostify** [comment]
Thank you so much, that helped clear things up @epoberezkin :)

**Comment by epoberezkin** [comment]
One group of use cases when you must use ref is when your schema is recursive - when the child can reference the parent - the schema for any tree-like structure, objects of unlimited depth (e.g. schema itself), etc.
