### ISSUE TITLE
In what way should I use a dynamic value for default?

### ISSUE THREAD

**Issue by pioneer32** [ajv-validator/ajv#162]
Hi, everyone!
I faced a necessity that is having a dynamic default value. Particularly, I'd like to use the current timestamp as a default value for some property.
I looked through the manual and found the following phrase "The default behaviour is faster and it allows to have dynamic values in defaults, e.g. timestamp". So, according to the manual, it's possible. Unfortunately, I have found out no more information regarding that.
In what way it can be implemented?
Any advice will be highly appreciated.
Thx in advance )

**Comment by epoberezkin** [comment]
If your default is an object (or array) and you update some property in this object this will change the value that is used during the validation without recompiling the schema. It will also change all other validated instances that may lead to surprising results in asynchronous code. If validated instances are used/serialised in the same execution block it will be fine.

Please also note that the default behaviour will be to clone in v 4.0 (soon).

In general I think custom keywords are safer option for dynamic defaults (they can't be applied before validation of course so your schema should allow for an empty property).

**Comment by pioneer32** [comment]
Thank you for the answer!
My default value is a number (timestamp). I agree with you at all that using custom keyword is the safest way, but nothing regarding dynamic default value is mentioned in the description of addKeyword. Probably, I tried to find the answer in the wrong section of the manual.

**Comment by epoberezkin** [comment]
Numbers/strings are inserted as values, not as references, so they won't be dynamic.
Custom keywords allow you to modify the data being validated, this allows to assign some default values or make any other changes to data.

**Comment by pioneer32** [comment]
As far as understand, the custom validator isn't invoked for missed properties. So, there is no opportunity to modify the data, isn't there?

**Comment by epoberezkin** [comment]
Correct, you'll have to use this keyword on the parent object level.

**Comment by pioneer32** [comment]
Ok. I got it. Thx you so much )

**Comment by epoberezkin** [comment]
You're welcome!

**Comment by modeswitch** [comment]
I just ran into this issue. Rather than use `ajv-keywords`, which doesn't work if your property is also required (from the docs: "the properties used in `dynamicDefaults` should not be added to `required` keyword (or validation will fail), because unlike `default` this keyword is processed after validation"), I do the following:

1. Add `dynamicDefault: true` to my schema wherever necessary. For example: `{ "type": "string", "format": "uuid", "dynamicDefault": true }`.
2. Pre-process my schema to replace instances where `dynamicDefault` is true with a `default` property the is a simple object that has `toJSON()` implemented. For UUID, the class looks like this: `class UUID { toJSON() { return uuid.v4() } }`.

When ajv sets default values, the class instance of UUID will return a new UUID each time it's invoked. This is handy because I can use a different class for each type/format. I'm using the same technique for `date-time` as well.

This is a bit of a hack, and will break if:

1. ajv starts caching default values (maybe assuming that they are constant)
2. ajv no longer invokes `toJSON()` on default values
