### ISSUE TITLE
Incorrect type definition in ```json-schema.d.ts```

### ISSUE THREAD

**Issue by DanilAndreev** [ajv-validator/ajv#1650]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Checked on ```"ajv": "^8.6.0"```

**Your typescript code**

In library file ```json-schame.d.ts```
```typescript
declare type StrictNullChecksWrapper<Name extends string, Type> = undefined extends null ? `strictNullChecks must be true in tsconfig to use ${Name}` : Type;

```

**Typescript compiler error messages**
Used ```"tsc": "^2.0.3"```
```
yarn run v1.22.10
$ yarn run build:compile && yarn run build:copyfiles
$ tsc
node_modules/ajv/dist/types/json-schema.d.ts:1:92 - error TS1005: '?' expected.

1 declare type StrictNullChecksWrapper<Name extends string, Type> = undefined extends null ? `strictNullChecks must be true in tsconfig to use ${Name}` : Type;
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ajv/dist/types/json-schema.d.ts:1:151 - error TS1005: ';' expected.

1 declare type StrictNullChecksWrapper<Name extends string, Type> = undefined extends null ? `strictNullChecks must be true in tsconfig to use ${Name}` : Type;
                                                                                                                                                        ~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
> Strange, but ```ts-node``` runs that code as expected.

**Describe the change that should be made to address the issue?**
Fix types  to use with ```tsc```.

**Are you going to resolve the issue?**

**Comment by Hypfer** [comment]
How was this fixed?

**Comment by werts** [comment]
any progress？

**Comment by epoberezkin** [comment]
it's not something that was fixed, likely incorrect settings (strictNullChecks must be true) or old tsc version (must be >4.2.3) or some other installation issue.

**Comment by Theinfinix500** [comment]
any news about this issue ?

**Comment by vigneshbarani24** [comment]
How should this be fixed ?

**Comment by harish-narayanasamy** [comment]
I have tried using     "strictNullChecks": true in tsconfig.json , but still got the error , and using tsc version 4.3.4 . May I know how this should be fixed ?

**Comment by epoberezkin** [comment]
I am going to close comments on this issue - it is not really defined what this issue was, and the issue may be that you simply have an incorrect schema or that JSONSchemaType has limitations and cannot be used in your case.

Please submit a new issue with a full code sample from a clear repository once you've checked the following:

1. strict mode is enabled in tsconfig.json (or at least strictNullChecks)
2. TS version is >= 4.2.3
3. you are importing the latest Ajv version (sometimes calling `npm install ajv` may install the previous version because some other dependency uses it - use `npm install ajv@8` and try clean install: `rm -rf node_modules && npm I`
4. check that your schema is indeed valid - that required properties are listed in "required", that optional properties have `nullable: true`, that "type" is set in all schemas - in many cases what was reported as JSONSchemaType issue was a user error where their schema was incorrect - it correctly shown compilation error.
5. Check other open issues related to JSONSchemaType - there are some known limitations.

A simple temporary workaround to use Ajv without using JSONSchemaType - it is optional.
