### ISSUE TITLE
Add types for draft-04 to ajv or a separate package

### ISSUE THREAD

**Issue by StephanBijzitter** [ajv-validator/ajv#1694]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Latest version, at the moment of writing `8.6.0`.

However, I also use `MongoDB` and the schemas that it wants should be formatted according to `draft-04`, the types for which I can only get when installing `ajv` at major version `6`.

I don't want to downgrade, though. Especially because every other part of the application relies on the latest and greatest JTD.

**Describe the change that should be made to address the issue?**
Adding the types (just the types!) for `draft-04` to the latest release would allow me to do something like:
```
import {JSONSchemaType} from "ajv/dist/types/json-schema-draft-04";
```
But crucially, it would not increase the bundle size for anyone.

**Are you going to resolve the issue?**
If this sort-of-feature-request is accepted, I can give it a shot!

**Comment by erikbrinkman** [comment]
Generally, I agree that it should be possible to have a `JSONSchemaType` for every version of JSON Schema that Ajv can parse. This would be much better than the version now which kind of allows anything.

What's not clear is the best way around this. Splitting up into several files works, but the validation functions would still need to import them, which could ultimately slow type checking if the compiler has to check another difficult overload. I'm not actually sure how typescript works here from a perf perspective, although if you know something please share it. I don't think @epoberezkin has implemented performance testing for the type checking (although it seems like a worth-while addition). Splitting also has the downside of maintainability and code reuse. Since the type is so complicated, there are a fair number of bugs in edge cases that still exist, and having to patch them in several different implementations would be rough, and more effort to test.

It's not clear that a single type with say a parameter to switch versions actually addressed many of these problems, and flags to change compatibility may also make the type even more complicated.

I think I'd ultimately want @epoberezkin's take. Part of me really wants to redesign `JSONSchemaType` from the ground up, which includes tackling this issue, and part of is way too lazy. Another part thinks if you build in a benchmark and show that it doesn't hurt the default case, copying the schema and making it only -draft-04 compatible is a reasonable solution in the short term.

On a related note, what specifically is not working with the trunk `JSONSChemaType` that would need to for -draft-04? I'm curious if there might be other simpler stop gaps or solutions to compatibility besides full schema support.

**Comment by epoberezkin** [comment]
Given that Ajv itself doesn’t support draft-04 it seems wrong to have this type here…

I’ve made a separate package with draft-04 support for backward compatibility, maybe it could be there, but I also don’t like maintaining two (or more versions)

Parameterizing doesn’t seem to be the answer too…

I think it to some extent overlaps with the question in another ticket - when/if 2019/2020 will become the main version. Currently JSONSchemaType is a hybrid (supporting both draft-07 and some parts of the later spec) and I’d keep it like that until JSON Schema stabilises as RFC.
