### ISSUE TITLE
Log warnings despite strictSchema: false

### ISSUE THREAD

**Issue by leonheess** [ajv-validator/ajv#1706]
https://ajv.js.org/options.html#strict-mode-options says `strictSchema: 'log'` displays log warnings and `strictSchema: false` does not. But even though I am using `strictSchema: false`, I still get log warnings.

**Comment by epoberezkin** [comment]
What exactly is the warning? strict: false should suppress all of them, strictSchema suppressed a particular subset - the details are in the doc on strict mode: https://ajv.js.org/strict-mode.html

**Comment by leonheess** [comment]
![image](https://user-images.githubusercontent.com/13834296/126609100-29bca403-c983-4b15-b0ce-f68f7dc1f910.png)

Does that mean I have to disable something else? I want it to ignore unknown formats but check known ones.

**Comment by epoberezkin** [comment]
You need to define them as noop (int64: true) one by one, there is no way to indiscriminately ignore all unknown formats - it would make you miss typos.

**Comment by epoberezkin** [comment]
It’s an unrelated issue btw, it’s all covered in the docs.

**Comment by leonheess** [comment]
I studied the docs but I couldn't find a way to disable this behavior. I can only turn off all format checking but that's not what I want. I need logging and format checking but I want to ignore all unknown formats. Unfortunately, I can't whitelist because I dont't know what formats people will submit.

**Comment by epoberezkin** [comment]
This is currently not supported. The premise here is that a hard failure is better than undefined behaviour - even for user defined schemas, where the users would probably expect formats do something rather than be quietly ignored.

> Unfortunately, I can't whitelist because I dont't know what formats people will submit.

it’s not that difficult actually - you can iterate the schema, e.g. with json-schema-traverse that ajv uses internally, and extract all used formats from the schema
