### ISSUE TITLE
Add option to silent "resolves to more than one schema" errors

### ISSUE THREAD

**Issue by pateketrueke** [ajv-validator/ajv#1707]
**What version of Ajv you are you using?**

v6.12.6

**What problem do you want to solve?**

I have a schema with their references inlined, those still have their `id`, e.g.

```js
const Ajv = require('ajv@6.12.6')
const s = [{
  "id": "Test",
  "type": "object",
  "properties": {
    "rel": {
      "id": "Rel",
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      }
    }
  }
}, {
  "id": "Rel",
  "type": "object",
  "properties": {
    "value": {
      "type": "string"
    }
  }
}]

const ajv = new Ajv({
  validateSchema: true,
  addUsedSchema: false,
  schemaId: 'auto',
  schemas: s,
});

const valid = ajv.validate({ "$ref": "Test" }, {});

valid
```

I'm getting `Error: schema with key or id "Rel" already exists` above.

> ⚠️ On v8.6.2 I got `Error: schema with key or id "" already exists` instead.

If I rename one of the `Rel` schemas to something else, it validates, but in the actual code I'm not expecting to manipulate the schemas in order to achieve that.

**What do you think is the correct solution to problem?**

Looking at the code, there is a call to a uniqueness validation, if we provide an option to skip duplicated schemas instead of throwing an Error it would be wonderful, e.g.

```diff
  key = resolve.normalizeId(key || id);
+ try {
  checkUnique(this, key);
+ } catch (e) {
+   // if we don't explicitly skip duplicates, then rethrow
+   if (!this._options.skipNestedDuplicates) throw e;
+   return;
+ }
  this._schemas[key] = this._addSchema(schema, _skipValidation, _meta, true);
```

> In my use case that fits perfectly and is what I would expect from actual options.

**Will you be able to implement it?**

Yes, of course.

**Comment by epoberezkin** [comment]
1. 6.12.6 is out of support - only security issues will be addressed
2. in draft7 it's $id rather than id, that's why it doesn't see it.
3. you cannot have multiple schemas with the same $id (or without $id).
4. there is no reason in your case to have this schema twice - you could just use `{$ref: "Ref"}` instead of inlining the second schema into the first. Alternatively you can pass only the first schema, the second schema would be available anyway
5. I believe you should be able to just do `ajv.validate("Test", {})`

**Comment by epoberezkin** [comment]
on the option idea, it doesn't seem necessary tbh

**Comment by theahura** [comment]
Sorry to reopen a long closed thread, but I ran into this problem too. In my case, with regards to schema composition. Say I have a schema structure like so:
```
const commonSubSchema = {
  $id: '/common_sub_schema',
  type: 'object',
  properties: { ... }
  required: [ ... ]
}
```
which then gets used in multiple schemas like:
```
const Foo = {
  $id: '/foo',
  type: 'object',
  properties: { 'sub': { $ref: '/common_sub_schema' } }
  definitions: {
    commonSubSchema
  }
}

const Bar = {
  $id: '/bar',
  type: 'object',
  properties: { 'sub': { $ref: '/common_sub_schema' } }
  definitions: {
    commonSubSchema
  }
}
```
and then THOSE get rolled into some higher level composition, like:
```
const Baz = {
  $id: '/baz',
  type: 'object',
  properties: { 'foo': { $ref: '/foo' }, 'bar': { $ref: '/bar' }
  definitions: {
    foo,
    bar
  }
}
```
this would cause the same error as mentioned above, even though the subschemas being called out are themselves identical. 

(Inb4 I prefer inlining the subschema definitions into the parent schemas because it makes it easier to modify the `required` field on the fly -- that is, _if_ requirements work the way I think they do in ajv)

**Comment by moyarich** [comment]
ran into this problem as well when trying to validate the [Custom Field](https://rjsf-team.github.io/react-jsonschema-form) example from [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form)

```
{
  "title": "A registration form",
  "description": "A custom-field form example.",
  "type": "object",
  "definitions": {
    "specialString": {
      "$id": "/schemas/specialString",
      "type": "string"
    }
  },
  "properties": {
    "mySpecialStringField": {
      "$ref": "#/definitions/specialString"
    },
    "mySpecialStringArray": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/specialString"
      }
    }
  }
}
```

**Comment by Carlos-err406** [comment]
i have the same issue as @theahura
