### ISSUE TITLE
Types of properties unknown using JTDDataType with 2020-12 $defs

### ISSUE THREAD

**Issue by java-james** [ajv-validator/ajv#1713]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
 
`8.6.2`

**Description**

Defining a schema with [2020-12](https://json-schema.org/draft/2020-12/json-schema-validation.html) "$defs" instead of "definitions" key will result in types being unknown.

**Describe the change that should be made to address the issue?**

Use $defs field instead of definitions for the following type:
```
export type JTDDataType<S> = S extends {definitions: Record<string, unknown>}
  ? JTDDataDef<S, S["definitions"]>
  : JTDDataDef<S, Record<string, never>>
```
This may need to be seperate and exported as part of 2020

**Are you going to resolve the issue?**

Happy to help if required

**Comment by epoberezkin** [comment]
JTDDataType is provided to construct the type of the data from the type of the JTD schema, it cannot be used with JSON Schema.

**Comment by epoberezkin** [comment]
(meaning that you cannot use $defs, it’s not part of JTD)

**Comment by java-james** [comment]
Thanks for your reply this makes sense.

**Comment by java-james** [comment]
Thanks for your reply. Understand!

**Comment by sacummings91** [comment]
Hey @epoberezkin just wanted to add on to this as I'm having the same problem but with `array` type. 
Something like this:
`
foo: {
      type: "array",
      items: {
        type: "string",
      },
    },
    `
evaluates to `unknown` as well. Is this expected behavior? I looked through `jtd-schema.d.ts` and it seems like this is expected as I don't see an option for "array" but just wanted to confirm here to be sure.

**Comment by epoberezkin** [comment]
@sacummings91 your example is JSON Schema, not JTD

**Comment by sacummings91** [comment]
I see, I did not realize that they were two different schema languages. So the issue here is that I am using JSON Schema format with `JTDDataType` utility and that is why they are incompatible? 

I wanted to use `JTDDataType` because I did not want to have to define interfaces for my expected shapes. I found it very useful to be able to do this when compiling my validators: `ajv.compile<JTDDataType<typeof schema>>`. It does not seem like that is supported with `JSONSchemaType` utility. 

We are treating the entities in the response from a GO server as `unknown` and using AJV to do compile/runtime validation on the expected shape. Then once they have been validated we translate them to a more Javascript/React friendly shape. 

Are you able to recommend which schema language is best suited for this? Any guidance would be appreciated.

**Comment by epoberezkin** [comment]
> I wanted to use JTDDataType because I did not want to have to define interfaces for my expected shapes.

JSON Schema is much more complex and, in general case, it is not possible to unambiguously derive type interface from the schema.

> Are you able to recommend which schema language is best suited for this?

This doc might be helpful to decide: https://ajv.js.org/guide/schema-language.html#comparison

Since it was written - I’d probably scratch off “brand new” from JTD - I see some ajv users using it (or at least trying), we also started using it in production in a couple of services at @wagestream - we also use compiled parsers for JSON strings in the requests body.
