### ISSUE TITLE
JTDDataType and parseDate

### ISSUE THREAD

**Issue by xhebox** [ajv-validator/ajv#1780]
**What version of Ajv you are you using?**

8.6.3

**What problem do you want to solve?**

While `allowDate` and `parseDate` will parse and serialize `Date` objects, `JTDDataType` always return `string | Date` type for `timestamp`.

It will lead to errors when you assign a field of type `JTDDataType<...>['date_field'] = string | Date` to a single field with either `string` or `Date` type.

**What do you think is the correct solution to problem?**

A helper option in `JTDDataType` like `JTDDataType<..., {timestamp: "date"}>`.

Or differential `string` or `Date` timestamp by two types. 

**Will you be able to implement it?**

No

**Comment by epoberezkin** [comment]
This is a type error, not a run time error - it can be resolved with “as” type cast.

I’m not convinced that it warrants complicating these type transformations that already push the boundaries of what TypeScript can do.

cc @erikbrinkman

**Comment by xhebox** [comment]
> This is a type error, not a run time error - it can be resolved with “as” type cast.
> 
> I’m not convinced that it warrants complicating these type transformations that already push the boundaries of what TypeScript can do.
> 
> cc @erikbrinkman

Yeah, it can be workarounded. I would appreciate that if I don't need to do the type cast.

But it is acceptable to close this feature request anyway, if you think it is not the case.

This problem comes from: there is a predefined interface. I wrote JTD for the interface. And I want to assign object of JTD type to the interface to confirm thay they are identical.

Of course, another choice would be using `JSONSchemaDataType`, which I did not use for some reasons.

**Comment by erikbrinkman** [comment]
This is an unfortunate downside of having native date support built into the jtd definition for ajv. Unfortunately, trying to shoehorn in other options like this would be hard, because they'd need to be passed all the way down, e.g. when you called compile you'd need to pass in these extra type options.

You could work around that by incorporating the option type into the AjvJTD object type. That should work and be reasonably elegant, but would require a significant retyping of the AjvJTD class (I think). I am unfortunately too busy to pursue such an undertaking, and since you aren't either, I think it's probably easiest to just do a cast.

If there are other reasons why the cast is hard (e.g. it's happening repeatedly or something), I'm willing to consider other solutions.

**Comment by erikbrinkman** [comment]
I should probably note that there's another risk to pursuing this if you change your mind. The compile and validate signatures are close to typescript's limits about how complex of types it will allow, so adding that flag may push it over the edge.

**Comment by xhebox** [comment]
> The compile and validate signatures ..

Agreed. Then I will cancel this feature request, it can be closed now. But maybe we could, instead, mention the problem in the document 🤔 ?
