### ISSUE TITLE
$ref with relative path does not use schema key as base for resolution (only uses schema ID)

### ISSUE THREAD

**Issue by HolgerJeromin** [ajv-validator/ajv#185]
I have some Schemas in different directories which are referring each others. 
All are fetched with XHR and put to ajv afterwards.
Below is a reduced test case:

```
<html>
<head>
<script type="text/javascript" 
  src="https://cdnjs.cloudflare.com/ajax/libs/ajv/4.0.5/ajv.bundle.js"></script>
</head>
<script>
var ajv = Ajv();
var secondschema  = {
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "properties": {
        "objectType": {
          "type": "string"
        }
    }
};

var firstschema = {
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "properties": {
        "angle": { "type": "number" },
        "substuff": {
            "type": "array",
            "items": { "$ref": "secondschema.Schema.json#" }
        }
    }
};

ajv.addSchema(secondschema, "/Schema/secondschema.Schema.json");
ajv.addSchema(firstschema, "/Schema/firstschema.Schema.json");
//real code has "/special/stuff/Schema/firstschema.Schema.json" and other schemas

var valid = ajv.validate("/Schema/firstschema.Schema.json", {"test": "me"});
// Uncaught Error: can't resolve reference secondschema.Schema.json# from id #

</script>
</html>
```

Is this a bug or am i doing something wrong?

**Comment by mol-repoman** [comment]
You either need to use IDs in schemas (in this case $ref's will be resolved as relative to these IDs) or to use absolute $ref's. As is, it's impossible to resolve these $refs. The key you pass to ajv as a second parameter is used for lookup, but it is not used as a base for ref resolution. Instead of using this second parameters you can add IDs in schemas.

**Comment by epoberezkin** [comment]
You either need to use IDs in schemas (in this case $ref's will be resolved as relative to these IDs) or to use absolute $ref's. As is, it's impossible to resolve these $refs. The key you pass to ajv.addSchema as a second parameter is used for lookup, but it is not used as a base for ref resolution. Instead of using this second parameters you can add IDs in schemas.

**Comment by HolgerJeromin** [comment]
Thanks for your answer. I will try tomorrow. 
Some code uses key and the id identically but I did not realized the difference in other parts. 

Is it possible to change ajv to support my code? tv4 worked with this schemas but is too slow for me, so I switched  :-)

**Comment by HolgerJeromin** [comment]
I have added the suggested workaround

```
if (schema.id === undefined) {
    schema.id = schemaFullname;
}
```

in my code. Works very nice. Thank you!
So the Problem is solved for me right now.

**Comment by epoberezkin** [comment]
Thank you. I will think whether this key should be used as id (the base for ref resolution). There are arguments for and against it...

**Comment by epoberezkin** [comment]
I don't think it is a good idea to use externally defined schema name as the base for $ref resolution:
- it is not clear where the $ref would resolve from the schema itself - makes it more difficult to understand.
- the same schema can result in different validation logic depending on how it's added to the Ajv instance.
- it also seems against the standard that clearly mentions schema IDs as the base for $ref resolution.

Workaround above resolves the issue.
