### ISSUE TITLE
JTDSchemaType has Typescript error with valid JTD

### ISSUE THREAD

**Issue by MichaelJCole** [ajv-validator/ajv#1865]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

    "ajv": "^8.8.2",

** Code and error **

```
import Ajv, { JTDSchemaType } from 'ajv/dist/jtd'
const ajv = new Ajv()

// then 

export interface JumpSpec<P = unknown, T = unknown> {
  type: string
  uri: string
  param?: P
  mountAt?: string
  defaults?: T[]           // this array will caus the problem
}

const spec: JTDSchemaType<JumpSpec> = {
  properties: {
    type: { type: 'string' },
    uri: { type: 'string' },
  },
  optionalProperties: {
    param: {},
    mountAt: { type: 'string' },
    defaults: { elements: {} },    // <-- error 
  },
}
```

Typescript objects to 'elements' with : `(property) elements: {} Type '{}' is not assignable to type 'never'`

Looking at the spec:  https://datatracker.ietf.org/doc/html/rfc8927#section-2

I think elements can take the empty form from the CDDL:
```
   ; All JTD schemas are JSON objects taking on one of eight forms
   ; listed here.
   schema = (
     ref //
     type //
     enum //
     elements //
     properties //
     values //
     discriminator //
     empty //
   )
...

   ; elements describes the "elements" schema form.
   elements = ( elements: { schema }, shared )
```

Which makes me think it's a bug :-)

Thanks for your awesome validation library!

**Comment by MichaelJCole** [comment]
I tried an alternate implementation, making the P and T generics more specific, and got a different error:
```
export interface JumpSpec2<
  P extends Record<string, unknown> = Record<string, unknown>,
  T extends Record<string, unknown> = Record<string, unknown>,
> {
  type: string
  uri: string
  param?: P
  mountAt?: string
  defaults?: T[]
}


const spec: JTDSchemaType<JumpSpec2> = {
  properties: {
    type: { type: 'string' },
    uri: { type: 'string' },
  },
  optionalProperties: {
    param: {},
    mountAt: { type: 'string' },
    defaults: { elements: {} },
  },
}
```
Below are the errors.  It looks like it's not accepting the 'empty' form and trying to use the 'values' form instead.

![image](https://user-images.githubusercontent.com/1504790/147279545-9eab10a5-d637-46fd-864d-f25af4dc24ce.png)

![image](https://user-images.githubusercontent.com/1504790/147279588-34b42809-1dc4-43f0-a83c-96e7f5edbcaf.png)

**Comment by MichaelJCole** [comment]
For me a workaround was to use the type `const spec: SchemaObject` instead of `JTDSchemaType<T>`.

**Comment by epoberezkin** [comment]
I don't believe it is possible to extend JTDSchemaType to allow constructing schema types out of parameterised types. The reason for that is that the data type dictates the shape of the schema, and it can be completely different depending on the values of P and T.

I am not that advanced in typescript, but I think typescript should evaluate JTDSchemaType not at a point where P and T are defined, but on the spot, I don't think it's possibly to delay this evaluation...

cc @erikbrinkman - am I writing some nonsense here or is it about correct? :)

**Comment by erikbrinkman** [comment]
What you're writing makes sense, but is actually nonsense 😅 . Typescript doesn't allow parametrized types to actually be used, you need to make them "concrete". In this example, both `P` and `T` have default definitions, so you can think of it like:

```
export interface DefaultJumpSpec2 {
  type: string;
  uri: string;
  param?: Record<string, unknown>;
  mountAt?: string;
  defaults?: Record<string, unknown>[];
}
```
in JTD, the correct schema for `Record<string, unknown>` is `{ values: {} }`, thus if you fix your schema to be:
```
const spec: JTDSchemaType<JumpSpec2> = {
  properties: {
    type: { type: 'string' },
    uri: { type: 'string' },
  },
  optionalProperties: {
    param: {
        values: {}
    },
    mountAt: { type: 'string' },
    defaults: { elements: { values: {} } },
  },
}
```
it then compiles fine.

Note: this was called out in the error which is saying that `{}` is missing the key `values` to be compatible with `JTDSchemaType<Record<string, unknown>>`.

By not using `JTDSchemaType` you're implicitly using `JTDDataType` under the hood, which should be parsing `param` and `defaults` as unknowns instead of as records. That's fine, but different from the interface you specified.

It's probably also worth noting that JTD doesn't have a way to specify `Record<string, never>` which seems like it was maybe what you intended. For that you'll need a more powerful verifier (like JSON Schema) to guarantee that there are no keys.

**Comment by MichaelJCole** [comment]
@epoberezkin @erikbrinkman Thank you, this is super helpful!
