### ISSUE TITLE
strict mode fails to validate number keywords when using $ref

### ISSUE THREAD

**Issue by lipkau** [ajv-validator/ajv#1898]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`8.10.0`

**Your code**

```javascript
const Ajv = require("ajv")

const schema = {
  type: 'object',
  properties: {
    foo: {
      $ref: 'foo.json/definitions/foo',
      minimum: 0,
      maximum: 100
    },
  }
};

const fooSchema = {
  $id: "defs.json",
  definitions: {
    foo: { type: "integer" }
  }
}

const ajv = new Ajv();
const validate = ajv.addSchema(fooSchema).compile(schema);

const valid = validate({ foo: 10 });
if (!valid) console.log(validate.errors);
```

**Validation result, data AFTER validation, error messages**

```
strict mode: missing type "number" for keyword "maximum" at "#/properties/foo" (strictTypes)
strict mode: missing type "number" for keyword "minimum" at "#/properties/foo" (strictTypes)
```

**What results did you expect?**

Validation should work just as if the `type` was defined in the original schema instead of the `$ref`.
![image](https://user-images.githubusercontent.com/4992870/153881806-4b350086-0e90-45ed-ad3e-89123cb52b16.png)

**Are you going to resolve the issue?**
no

**Comment by epoberezkin** [comment]
This is not a bug, this how it is supposed to work - the type keyword in strict mode must be in the same schema or in the parent schema(s), not in a sibling schema or via $ref.

Two reasons:
1) think about it as about type declaration for the compiler - it’s expected in the same module, not in some other place, and in some cases you have to declare the type more then once.
2) it would be very complex to track types via refs :)…

**Comment by brunobastosg** [comment]
@epoberezkin sorry to comment on a closed issue.

I have this same problem with strict mode. I have defined a custom currency type as a schema:

```
{
    "$id": "currency",
    "type": "string",
    "format": "currency",
    "maxLength": 17
}
```

The "currency" format is defined by me in another file, but it's not important for my problem.

Then, I defined the following keyword:

```
export const keywordCurrencyValueGreaterThan: KeywordDefinition = {
  keyword: 'currencyValueGreaterThan',
  type: 'string',
  schemaType: 'string',
  validate: validateFunction, // code not important
  errors: true
};
```

Now if I use the following schema:

```
{
  type: 'object',
  properties: {
    invoiceValue: {
      $ref: 'currency',
      currencyValueGreaterThan: '100,00'
    }
  },
  required: ['invoiceValue']
}
```

Then I get the warning `strict mode: missing type "string" for keyword "currencyValueGreaterThan" at "#/properties/invoiceValue" (strictTypes)`, as the OP described in this issue.

I know it is not a bug, but is there an alternative way to achieve this behavior (custom type + custom keyword) without the need to add the "type" again (since it's already in the custom type)?
