### ISSUE TITLE
oneOf validate failed

### ISSUE THREAD

**Issue by Pana** [ajv-validator/ajv#1934]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.10.0

**Ajv options object**

```javascript
{}
```

**JSON Schema**

```json
{
  "title": "Block object",
  "type": "object",
  "required": [
    "transactions"
  ],
  "properties": {
    "transactions": {
      "oneOf": [
        {
          "title": "Full transactions",
          "type": "array",
          "items": {
            "title": "Signed 1559 Transaction",
            "type": "object",
            "required": [
              "chainId",
              "input"
            ],
            "properties": {
              "input": {
                "title": "input data",
                "type": "string",
                "pattern": "^0x[0-9a-f]*$"
              },
              "chainId": {
                "title": "chainId",
                "type": "string",
                "pattern": "^0x([1-9a-f]+[0-9a-f]*|0)$",
                "description": "Chain ID that this transaction is valid on."
              }
            }
          }
        },
        {
          "title": "Transaction hashes",
          "type": "array",
          "items": {
            "title": "32 byte hex value",
            "type": "string",
            "pattern": "^0x[0-9a-f]{64}$"
          }
        }
      ]
    }
  }
}
```

**Sample data**

```json
{
  "transactions": []
}
```

**Your code**

```javascript
const ajv = new Ajv();
const blockSchemaValidator = ajv.compile(schema);
const valid = blockSchemaValidator(block.result);
```

**Validation result, data AFTER validation, error messages**

```
// valid: false
[
  {
    instancePath: '/transactions',
    schemaPath: '#/properties/transactions/oneOf',
    keyword: 'oneOf',
    params: { passingSchemas: [Array] },
    message: 'must match exactly one schema in oneOf'
  }
]
```

**What results did you expect?**
The result should pass , because the transactions field is an empty array

**Are you going to resolve the issue?**
Not Sure

**Comment by Pana** [comment]
Currently, if the transactions field is not empty for example is a hash array it will pass. Actually it also should pass if transactions are an empty array.

**Comment by JacobLey** [comment]
It would be easier to review with a more minimal schema, but on my review it appears that this is an expected behavior.

Both `oneOf` schemas are an array, just with different items. But neither specifies a `minItems` or something like that to disqualify an empty array. So your example data with an empty array validates against both, hence failing validation for `oneOf`.

There are a couple ways to go about this, but I'd recommend just adding a `minItems: 1` to one of your array schemas. That will disqualify it from validation, and allow the other to pass as the only valid schema in `oneOf`.

Alternatively could switch to `anyOf` instead of `oneOf`. The only case where both are valid is empty _should_ be an empty array, which sounds fine? I suspect that is a slight performance gain as well, because AJV internals can skip the second schema if the first is valid

So it looks like a bug in your schema, not AJV

**Comment by epoberezkin** [comment]
@JacobLey thank you!

**Comment by Pana** [comment]
@JacobLey @epoberezkin I have simple the schema and data.
My point is the `transactions` can be an empty array, this should be right, how do I define the schema for this situation ?

**Comment by JacobLey** [comment]
`[]` is valid for both your "Full transactions" and "Transaction hashes" schemas.
In the same way that `[].every(() => false) === true`.

`oneOf` is an XOR, so if both are truth, it resolves to false.

So you need to either allow both to be true (`anyOf`) or make an empty array false for one schema (`minItems: 1`). I'm sure there are other ways to implement as well

**Comment by Pana** [comment]
Thanks @JacobLey
