### ISSUE TITLE
add strict `additionalProperties`

### ISSUE THREAD

**Issue by swantzter** [ajv-validator/ajv#1936]
## What version of Ajv you are you using?

8.10

## What problem do you want to solve?

We want to be able to pass data to validate() and without having to turn on any modifying functionality (`removeAdditional`) be sure that the data we're validating only has the requested properties unless specifically and explicitly asked for additional ones.

## What do you think is the correct solution to problem?

extend the available strict mode options with a `strictAdditional` that forbids additional properties unless `additionalProperties` is set to true or a schema in the schema.

```js
const ajv = new Ajv({ strictAdditional: true })
let validate = ajv.compileSchema({ properties: { a: { type: 'string' } } })
validate({ a: 'hi' })
// > true
validate({ a: 'hi', b: 'hello' })
// > false

validate = ajv.compileSchema({ properties: { a: { type: 'string' } }, additionalProperties: true })
validate({ a: 'hi' })
// > true
validate({ a: 'hi', b: 'hello' })
// > true
```

## Will you be able to implement it?

If someone can point me in the right direction, maybe.

**Comment by epoberezkin** [comment]
This is a change to JSON Schema specification - won’t be done, sorry. You may look into JTD spec that ajv also supports and that has exactly the semantics for additionalProperties that you ask - prohibited by default, only allowed with additionalProperties: true.

See this comparison: https://ajv.js.org/guide/schema-language.html#comparison

“Brand-new” is no longer the case - it’s supported since January 2021, and I used it on a high traffic service, both for validation and request body parsing.
