### ISSUE TITLE
how can I use swagger spec definitions

### ISSUE THREAD

**Issue by g00fy-** [ajv-validator/ajv#195]
Is there any easy way I could validate data against definitions from swagger spec ?

``` javascript

import test from 'ava';
import ajv from 'ajv';

const swagger = {
    "swagger": "2.0",
    "definitions": {
        "Employee": {
            "required": [
                "name"
            ],
            "properties": {
                "image": {
                    "$ref": "#/definitions/Image"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "Image": {
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}

const schema = ajv({
    schemas: swagger.definitions,
    removeAdditional: true
});

test(t => {
    var isValid = schema.validate('Employee', {
        name: "John"
    })
    t.equa(isValid, true);
});
```

the result is:

``` javascript
   1 failed

  1. [anonymous]
  failed with "can't resolve reference #/definitions/Image from id #"
      Object.generate_ref [as code] (node_modules/ajv/lib/dotjs/ref.js:62:22)
    Object.generate_validate [as validate] (node_modules/ajv/lib/dotjs/validate.js:374:37)
    Object.generate_properties [as code] (node_modules/ajv/lib/dotjs/properties.js:193:26)
    generate_validate (node_modules/ajv/lib/dotjs/validate.js:374:37)
    localCompile (node_modules/ajv/lib/compile/index.js:53:22)
    Ajv.compile (node_modules/ajv/lib/compile/index.js:42:10)
    _compile (node_modules/ajv/lib/ajv.js:294:29)
    getSchema (node_modules/ajv/lib/ajv.js:184:51)
    Ajv.validate (node_module
```

**Comment by epoberezkin** [comment]
This will work:

```
var ajv = require('ajv')({ removeAdditional: true });
ajv.addSchema(swagger, 'swagger.json')
var isValid = ajv.validate({ $ref: 'swagger.json#/definitions/Employee' }, {
  name: "John"
});
```

**Comment by g00fy-** [comment]
thanks!

**Comment by colmaengus** [comment]
I would like to use a swagger definition where the body parameter for post uses a reference to a definition.

``` json
[{
          "name": "body",
          "in": "body",
          "description": "new device",
          "required": true,
          "schema": {
            "type": "object",
            "additionalProperties": false,
            "required": ["type"],
            "properties": {
              "$ref": "#/definitions/device/properties"
            }
          }
        }]
```

The reason for doing it this way is that we also have a PATCH method where the set of required properties are different to POST.
I've loaded the full swagger.json as in your above example.
I've tried using the following but its not resolving the reference:
.validate({$ref: 'swagger.json#/paths/devices/post/parameters[0]'}, req.body)
I'm getting the following error: "can't resolve reference swagger.json#/paths/devices/post/parameters[0] from id #"

**Comment by colmaengus** [comment]
Should have spent more time looking at the json pointer spec.
The following works: $ref: 'swagger.json#/paths/~1devices/post/parameters/0'

**Comment by epoberezkin** [comment]
`$ref` can be used as a schema for a single property, not to the whole `properties` keyword. In your example `$ref` will be treated as a property name, not as a reference to something.

**Comment by dinvlad** [comment]
@epoberezkin, your example works well both for body parameters and other types (e.g. header). But can it be done through `validate()` returned from `ajv.compile`?
```
const validate = ajv.compile(swagger);
...
var isValid = validate({ $ref: '#/parameters/BodyParameter' }, {
  name: "John"
});
```
instead of
```
const validate = ajv.addSchema(swagger, 'swagger.json');
...
var isValid = validate({ $ref: 'swagger.json#/parameters/BodyParameter' }, {
  name: "John"
});
```
The second example works for me, but I'd like to avoid `addSchema()` because I call `compile()` inside my function on every call, and rely on its caching (so that call is idempotent). `addSchema()` on the other hand may only be called once per spec, and so I have to put it somewhere else (e.g. global context, which is then hard to test). In addition, `validate()` syntax is just shorter (no need to assign a schema id).

But the first form then returns 'true' irrespective of the value of `$ref` (I can even feed it with a non-existant reference, e.g. `'#/hello/world'`) or the body. So it looks like in this case `$ref` is really treated as another property, not as a reference.

**Comment by colmaengus** [comment]
we ended up sending de-referencing the swagger.json using https://www.npmjs.com/package/json-schema-ref-parser and then fed the required schema part of the swagger to ajv for validation.

**Comment by dinvlad** [comment]
(Sorry, deleted previous comment since I found a solution). Nice, in my case I'd like to use `compile()` instead of `addSchema()` for idempotency, but `compile()` doesn't assign an 'id' (or rather, it uses an empty 'id' if I'm correct). To get it working with the `validate({ $ref: ...` syntax, I had to
```
ajv.compile(Object.assign({$id: 'spec'}, swagger));
...
ajv.validate('spec#/parameters/BodyParameter/schema', body);
// or ajv.validate('spec#/parameters/HeaderParameter', headerValue);
```
Here I still used the full `ajv.validate()` instead of `validate()` returned from `compile()`, otherwise it 'succeeds' validation even for invalid inputs or parameter refs.

**Comment by epoberezkin** [comment]
@dinvlad why do you want to call compile/addSchema every time? It can be called only once during app initialisation.

**Comment by dinvlad** [comment]
That simplifies testing, e.g. when I need to pass a fake schema I cannot just `ajv.addSchema(swagger, 'spec')` in the global context. I could do it in a function, but then we're back to square one :) Or maybe the solution is more obvious and I just don't see it :)

**Comment by pbelamkar** [comment]
> This will work:
> 
> ```
> var ajv = require('ajv')({ removeAdditional: true });
> ajv.addSchema(swagger, 'swagger.json')
> var isValid = ajv.validate({ $ref: 'swagger.json#/definitions/Employee' }, {
>   name: "John"
> });
> ```

In this Case if i want compare whole schema with api response instead of only name :"John" then how to define this. Because i am defined like this but it's not validating. 
let validate = ajv.validate({ $ref: 'swagger.json#/definitions/AccountUser' },responseData);
