### ISSUE TITLE
Schema stacking and resolution chaining?

### ISSUE THREAD

**Issue by target-san** [ajv-validator/ajv#199]
Hello,

I wonder if it's possible to perform kind of schema stacking, analogous to OOP inheritance. The simplest case is, you add schema under empty ID, and when you compile new validator, any references in compiled schema will first look in that schema, and then in added base schema. Per what I found, reference resolution won't consider local references span to anything other than current schema.

Thanks

**Comment by epoberezkin** [comment]
It won't indeed... It's definitely outside of spec. You can do something like this using custom keywords though I think, although it's not trivial.

If you were to do it, where would the inheritance structure exist? In the schema? Or just in ajv instance? Custom keyword would work in both cases, just curious how you see it.

**Comment by target-san** [comment]
I meant this as ajv's feature. The simplest case would be

```
ajvInstance.addSchema(someSchema, '');
// ...
var validator = ajvInstance.compile({ $ref: '#/path/in/someSchema' });
```

Here, any local references in compiled schema are first resolved against schema itself and then against some registered schema with empty ID. This isn't something really important, just kind of sugar.

**Comment by epoberezkin** [comment]
Consider how would anybody understand where this reference points to. Local reference should be local, remote should point to the exact location, otherwise it will be very confusing. Any inheritance if implemented should be expressed in the schema itself, definitely not as a validator feature.

The right place to submit this idea would be [json-schema-org](https://github.com/json-schema-org/json-schema-spec). If the idea makes its way into a standard draft (or at least becomes a proposal with a clearly defined syntax and some community support), I may implement it in ajv.
