### ISSUE TITLE
undefined top-level value is considered valid

### ISSUE THREAD

**Issue by DanielSWolf** [ajv-validator/ajv#2067]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

I'm using version 8.11.0, which is the latest.

**Ajv options object**

```javascript
{ strict: true }
```

**JSON Schema**

```json
{}
```

**Sample data**

```javascript
undefined
```

**Your code**

Repro: https://runkit.com/danielswolf/ajv-issue-undefined

**Validation result, data AFTER validation, error messages**

```
`true` (value is valid)
```

**What results did you expect?**

I expected `undefined` not to be a valid value against the schema `{}`. It is my understanding that this schema allows any valid JSON value, which `undefined` is not.

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
this is not a bug really, this is by design - empty schema is treated as "no validation rules", so it would accept any value - not only valid JSON values.

Ajv can be (and is) used in many scenarios beyond JSON validation, and the only reliable way to restrict object value to representable in JSON is to parse JSON string... a simple solution would be to define schema as `{type: ["number", "string", "array", "object", "boolean", "null"]} - that would restrict to JSON values.
