### ISSUE TITLE
Cannot import Ajv

### ISSUE THREAD

**Issue by njfamirm** [ajv-validator/ajv#2111]
when I import Ajv in typescript
```ts
import Ajv from 'ajv/dist/ajv.js';
```

chrome return this error
```
Uncaught SyntaxError: The requested module './../../node_modules/ajv/dist/ajv.js' does not provide an export named 'default' (at validator.ts:1:8)
```

why does this issue happen?

thanks

**Comment by tvsbrent** [comment]
I don't think this is a great solution, but the way I worked around this is to change the extension of my TypeScript file to be `.cts`. That tells TypeScript to compile this a CommonJs file, and will give it a `.cjs` extension once compiled. My current project is not creating a single bundled file, and is only for server-side Node execution, so this solution may not work for you.

Anyway, once I did the above, I could do an import as you show, as well as import types. For example:

```TypeScript
import Ajv from 'ajv/dist/jtd.js';
import type { JTDDataType } from 'ajv/dist/jtd.js';

const ajv = new Ajv();
```

**Comment by njfamirm** [comment]
This is not a logical way
I can't repeat this every time I install ninety modules
This package; is not a small package
I wonder why I encountered this problem and did not find a solution

**Comment by GabenGar** [comment]
@njfamirm

> This is not a logical way

Nothing is logical about Node ESM support by typescript.

> I can't repeat this every time I install ninety modules

Repeat what? That's a typescript approved™ way of handling the difference between CJS and MJS.

> This package; is not a small package

How is it relevant to the module system of this package? You would have the same problem with a hello world written in an ESM typescript too.

> I wonder why I encountered this problem and did not find a solution

The underlying problem is typescript versioning being driven by marketing above all else, so it's perfectly possible the old type code randomly breaking in a minor/patch typescript release.

This issue is only going to get more pronounced as more packages support Node ESM, so when you have random import problems, try these steps first:
1. Try to call `default` key of the default import:
    ```typescript
    import name from "module-path"`;
    name.default();
    ``` 
2. Rewrite into the default import: `import { default as name } from "module-path";`
3. Rewrite into named import: `import { name } from "module-path";`

**Comment by njfamirm** [comment]
I fix it with rollup commonjs resolver!

**Comment by cyrfer** [comment]
@njfamirm thank you! It worked for me too, using Rollup v4.
