### ISSUE TITLE
Can't create JTDSchemaType from tagged union with no additional properties

### ISSUE THREAD

**Issue by jkav77** [ajv-validator/ajv#2123]
**What I'm trying to do**
I want to use the JTDSchemaType to create a schema for messages I will pass through a websocket. The messages have a `type` field used with a discriminator in the schema. Some of the messages require no additional information, such as a "ping" message, but I am getting an error when creating the `JTDSchemaType` unless there are additional properties.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v8.11

**Ajv options object**

```javascript
{}
```

**Your code**

```typescript
import Ajv, { JTDSchemaType } from "ajv/dist/jtd";

const ajv = new Ajv();

type Message = { type: "ping" } // causes error unless an additional property is added
            |  { type: "error"; message: string };

const schema: JTDSchemaType<Message> = {
  discriminator: "type",
  mapping: {
    ping: {
      properties: {}, // compile error because ping is type 'never'
    },
    error: {
      properties: {
        message: { type: "string" },
      },
    },
  },
};
```

**What results did you expect?**
I expect to be able to create a schema for a tagged union that has no properties except the tag. I can't compile this because typescript expects the mapping of `ping` to be type `never`.

**Are you going to resolve the issue?**
I'm not sure how, but I'm happy to help.

**Comment by epoberezkin** [comment]
cc @erikbrinkman :)

**Comment by erikbrinkman** [comment]
Thanks for finding this! Every time there's a bug I heave a sigh because it's partially caused by typescripts weird type system. In general typescript types are permissive, meaning `{ prop: type }` is a narrowing of the object enforcing that `prop` has `type` but the object could also have any other member set as well. This means that `{}` actually allows all objects as a type.

The only exception to this rule is with object literals, which can't specify extra members. That means when creating these schema types, since we're using them mainly for object literals, we're actually bending the type system behave in a way it doesn't normally.

For discriminators we remove the discriminator field from the definition with an `Omit`, but if there are no other properties this creates the empty object type `{}`. Ideally this would naturally fit a record, but most of the rules don't work since `{}` has the reverse assignability as one might expect.

There may be clever ways to handle this better, but the PR I submitted #2158 just special cases that object, since it's already tricky enough to work with..

**Comment by jkav77** [comment]
Thanks for explaining. Now I understand why it wasn't working before. I will keep track of the pull request so I can remove my hackish workaround when it gets merged.
