### ISSUE TITLE
 removeAdditional: 'failing' and `injectAdditionalProperties`

### ISSUE THREAD

**Issue by brettz9** [ajv-validator/ajv#2170]
**What version of Ajv you are you using?**

8.11.2

**What problem do you want to solve?**

I want to do one-off enforcement checks of `additionalProperties` as though it exists on all objects without imposing the schema requirement on all users. My own demo schemas should not have additional properties, but I am not inclined to impose this on users.

**What do you think is the correct solution to problem?**

Add an option to `removeAdditional` or an option in conjunction with `removeAdditional`

**Will you be able to implement it?**

No.

**Comment by epoberezkin** [comment]
Sorry, can you clarify what behaviour that would have?

**Comment by brettz9** [comment]
If `additionalProperties: false` did not exist on some objects, the option would nevertheless enforce it everywhere in the schema where objects were allowed.

**Comment by DavidEdell** [comment]
I second this idea.  In my case, I want to ensure a strict comparison on configuration files delivered to us that should not contain undocumented fields (which might mean a version mismatch even if technically valid), but still want to allow users to manually add additional fields during testing without issue.  My schema is autogenerated, so I may just generate 2 files for now as a workaround.


I don't think adding this as an option to removeAdditional makes sense, because the goal here is to add additional validation, not to alter the result, though implementation-wise it would probably be a part of the same logic.

I suggest adding a new 'strict mode' option `strictProperties: true` with the true/log/false/undefined values used for other strict fields.  If set, this mode would treat all objects as if the schema defined `additionalProperties:false`.

For my use case, I would set `strictProperties: "log"` and the single validation script would then be effective for all users, providing non-fatal warnings for any extra fields added.

**Comment by epoberezkin** [comment]
> If additionalProperties: false did not exist on some objects, the option would nevertheless enforce it everywhere in the schema where objects were allowed.

I understand now – thanks for clarifying. It has been suggested before, and it will not be added, as it is against the principle of avoiding schema modifications with options. The reason for that is that it undermines JSON Schema specification being, effectively, a DSL – this feature would change the semantics of this DSL.

You may generate or augment your schemas programmatically in your code, but it's out of scope for this library.

> I want to do one-off enforcement checks of additionalProperties as though it exists on all objects without imposing the schema requirement on all users.

There is `unevaluatedProperties` keyword in draft-2019 that solves that problem - you can define your schemas without it, and in place you use them you can extend them with this keyword:

```
{
  $ref: "your_schema_ref",
  unevaluatedProperties: false
}
```

**Comment by DavidEdell** [comment]
unevaluatedProperties sounds like it would address this use case, but doesn't seem to be actually working in ajv.  I get `strict mode: unknown keyword: "unevaluatedProperties"` when I try using it.  

That's true even with the example from the documentation at https://ajv.js.org/json-schema.html#unevaluatedproperties (which, btw is missing a comma in anyOf).

Am I missing something, or is this broken?

**Comment by epoberezkin** [comment]
you need to import from `ajv/dist/2019`, by default it's draft-07.

**Comment by DavidEdell** [comment]
Thanks.  It might be useful to mention that in the docs for those properties (unless you're about to update the default spec version to the latest).

Is there a supported way to import the specific dist via ESM?  The [doc](https://ajv.js.org/json-schema.html#json-schema-versions) only gives examples with the require keyword.  As a quick test, I had to use `import Ajv from "./node_modules/ajv/dist/2019.js";`


For future reference, a quick way of using this property as an optional check:
```
    const schema = JSON.parse( fs.readFileSync( schemafn ) );
    if (strict) {
        schema.unevaluatedProperties = false;
    }    
    const data = JSON.parse( fs.readFileSync( datafn ) );
    const valid = ajv.validate(schema, data)

```

**Comment by DavidEdell** [comment]
Actually, unevaluatedProperties does not seem to solve this for my use case.  It works perfectly at the top-level, but doesn't look to apply to nested objects.  Is there any way to specify this property to apply recursively to nested objects/arrays?
