### ISSUE TITLE
Strict Mode check not take account of $ref

### ISSUE THREAD

**Issue by chengB12** [ajv-validator/ajv#2199]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.11.2

**Ajv options object**
strict: true

Reproduce code:
```javascript
    new Ajv({
            strict: true,
        })
            .addSchema({
                $schema: 'http://json-schema.org/draft-07/schema#',
                $id: 'my-defs.json',
                definitions: {
                    Foo: {
                        type: 'object',
                        properties: {
                            foo: {
                                type: 'string',
                            },
                        },
                    },
                },
            })
            .compile({
                $schema: 'http://json-schema.org/draft-07/schema#',
                type: 'object',
                properties: {
                    nested: {
                        $ref: 'my-defs.json#/definitions/Foo',
                        additionalProperties: false,
                        // type: 'object', <=== add redundant type def will make error go away
                    },
                },
            })
```

**Your code**

**Validation result, data AFTER validation, error messages**
Got   strict mode: missing type "object" for keyword "additionalProperties" at "#/properties/nested"
```

```

**What results did you expect?**
no error
**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Yes, this is by design, you can see it as a limitation, but it is a useful one - it leads to a more modular schema design. $ref can be used in multiple contexts but it may be compiled into a separate validation function, so whatever restrictions that strict mode has will be applied to $refs in isolation of the containing schemas.

Also, you cannot really use additionalProperties like that because it only takes into account properties defined in the same schema object - additionalProperties: false in your case prohibits all properties. What you want can be achieved with unevaluatedProperties defined in draft-2019 of JSON Schema (you need to use different ajv import to use it, it won't change how strict mode treats refs though)
