### ISSUE TITLE
The message for additionalProperties isn't as helpful as others

### ISSUE THREAD

**Issue by arosequist** [ajv-validator/ajv#227]
For most errors, `dataPath` and `message` combine to form something that makes it easy to see what's wrong (which makes `errorsText` useful, since it concats those fields).

However, if you get an `additionalProperties` error, the property causing problems isn't included in the message.

In particular, could we change this:

``` js
{ keyword: 'additionalProperties',
  dataPath: '',
  schemaPath: '#/additionalProperties',
  params: { additionalProperty: 'extra_field' },
  message: 'should NOT have additional properties' }
```

to one of these instead?

``` js
{ keyword: 'additionalProperties',
  dataPath: '',
  schemaPath: '#/additionalProperties',
  params: { additionalProperty: 'extra_field' },
  message: 'should NOT have additional properties (extra_field)' }

{ keyword: 'additionalProperties',
  dataPath: '',
  schemaPath: '#/additionalProperties',
  params: { additionalProperty: 'extra_field' },
  message: 'should NOT have extra_field' }
```

I think the second option is particularly appealing, since it's very similar to other error messages, like `type`:

``` js
{ keyword: 'type',
  dataPath: '.bad_field',
  schemaPath: '#/bad_field',
  params: { type: 'number' },
  message: 'should be number' }
```

I can work on a PR if this is something that should be fixed.

(side-note: could we also make "NOT" lowercase in the message?)

**Comment by epoberezkin** [comment]
@arosequist thank you!

I suspect that this wording exists from the time when additionalProperties was returning a single error for all properties rather than one for each additional property (you can have multiple errors with `allErrors: true` option)...

Your suggestion can make it better in some cases, but it cannot be merged right now as it may break the code of users who depend on error messages. So in any case if we do it, it should be a major version change.

In general, the messages returned by Ajv were intended for consumption by code/debugging rather than for the end users. In particular for additionalProperties, I don't see a real use case when end users could add additional properties - it usually happens if the wrong data is supplied to the api. The error object has an additional property in params so any code that consumes it can use it there.

There are several ways to generate end-user messages:
- application code
- [ajv-i18n](https://github.com/epoberezkin/ajv-i18n). Its English locale already has "NOT" in lowercase, by the way. At the moment it doesn't allow adding/changing locales in the run time, so you'd have to fork it, but I'd be happy to change it to allow it - https://github.com/epoberezkin/ajv-i18n/issues/21
- custom error messages discussed in #100 (not implemented yet) - it should be a separate package defining the custom keyword errorMessages, there is even a small bounty for it :)
