### ISSUE TITLE
Do you plan to support AJV without eval?

### ISSUE THREAD

**Issue by sandrina-p** [ajv-validator/ajv#2285]
In your docs, you mention that [AJV uses `eval()`](https://ajv.js.org/security.html).

Do you plan to drop `eval` in a future release (besides the standalone version alternative)? Also, may I ask why does it need Eval?

**Comment by epoberezkin** [comment]
No, because Ajv compiles schemas into code - making this code executable in runtime environment requires Function constructor.

You can use standalone compilation and ship pre-compiled schemas with your code, then it won't use eval (and won't even use Ajv at run time - it will only use some functions from runtime folder).
