### ISSUE TITLE
JTDSchemaType error involving interface with arbitrary keys

### ISSUE THREAD

**Issue by zzaba** [ajv-validator/ajv#2303]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
```
8.12.0
```

**TypeScript code**
```typescript
interface Values { [key: string]: number }
const schema: JTDSchemaType<Values> = { values: { type: "int32" } };
```

**TypeScript error**
```
Type '{ values: { type: string; }; }' is not assignable to type 'never'. ts(2322)
```

**What results did you expect?**
> No errors

**Are you going to resolve the issue?**
> No

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "useUnknownInCatchVariables": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "exactOptionalPropertyTypes": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false
  }
}
```

Error is reproducible in deno.

**Related issues**
https://github.com/ajv-validator/ajv/issues/2169
https://github.com/ajv-validator/ajv/issues/2219
https://github.com/ajv-validator/ajv/issues/1588 (?)

**Comment by epoberezkin** [comment]
https://github.com/ajv-validator/ajv/blob/master/spec/types/jtd-schema.spec.ts#L190

Try type Values = Record<string, number>

cc @erikbrinkman

**Comment by erikbrinkman** [comment]
@zzaba what @epoberezkin say is correct, switching to a `Record` will fix this problem. The issue comes from the way index interfaces are interpreted in typescript.

When you wrote:
```
interface Values { [key: string]: number }
```
you would probably assume that `keyof Values` would be `string`, but it's actually `string | number`. This is because when you index an object with a number (or any type), the javascript spec says you first convert it to a string and then do the lookup, to the point where this is valid javascript: `["wut"][{ toString() { return "0"; } }]`.

Right now, typescript seems to interpret indexable interfaces as really `Record<string | number, ...>` rather than the more strict `Record<string, ...>`. I'm too lazy to look up the reference for this, but it probably has to do with legacy usage and the baggage of javascript.

For the sake of JTD, values should probably be only indexable by strings, rather than at least indexable by strings, but that's certainly up for debate. Ulysse might have more thoughts on this. I'm going to close for now, but @zzaba, reopen if you feel strongly about key permissibility.
