### ISSUE TITLE
Why regex pattern not works ?

### ISSUE THREAD

**Issue by pullmann4rent** [ajv-validator/ajv#2374]
Hello,

I want to use regex in AJV but it does not work. Can you say me what I am doing wrong ?

I tried this

```
      firstname: {
        type: 'string',
        pattern: '^[a-zA-Z\s]$',
        minLength: 1,
        maxLength: 60
      },
```

and this
```
      firstname: {
        type: 'string',
        pattern: '/^[a-zA-Z\s]*$/',
        minLength: 1,
        maxLength: 60
      },
```

**Comment by jasoniangreen** [comment]
The first example is the closest as you don't need the enclosing `/` since this is a string, not a regular expression literal. Your problem is that you need to double escape the `\s`. 

If you [review the docs for the pattern keyword](https://ajv.js.org/json-schema.html#pattern) you'll see you can test your pattern string easily using `new RegExp(str)` as that is what AJV uses.

e.g. `new RegExp('^[a-zA-Z\\s]$')`
