### ISSUE TITLE
Coercion of empty string to integer to convert to null

### ISSUE THREAD

**Issue by joaoreynolds** [ajv-validator/ajv#243]
When coercion is enabled, and empty string fails validation if the datatype must be an integer. Is it possible to convert empty strings to null when coercing to ints, numbers, etc?

**Comment by epoberezkin** [comment]
I am afraid it is a bit too late to change the coercion rules - it won't be backwards compatible. Also all the rules are created in such way that they are "reversible" - coercing twice should produce the same result as the original data. Doing it otherwise would make validation fail in cases when it should not.

Now it works this way: `"0"` -> `0` -> `"0"`, so it is reversible.

The coercion you suggest is not reversible: `""` -> `0` -> `"0"`.

By the way, empty string coerces to `null` but in JSON-schema it is a different type. See [all rules](https://github.com/epoberezkin/ajv/blob/master/COERCION.md).

To pass validation in your case you should simply update your schema, e.g. in such way:

```
{ "type": ["integer", "null"] }
```

If you need additional data change from `null` to `0` you can either do it outside of schema, use custom keyword or coerce twice (a bit weird but will work too):

```
{
  "description": "this schema will coerce empty string to 0",
  "allOf": [
    { "type": ["integer", "null"] },
    { "type": "integer" }
  }
}
```

**Comment by joaoreynolds** [comment]
Thank you! This is definitely a workaround I can live with.

P.S. I LOVE ajv - thanks for everything!

**Comment by epoberezkin** [comment]
Thank you
