### ISSUE TITLE
Bug: oneOf doesn't work properly when coerceTypes is true

### ISSUE THREAD

**Issue by foray1010** [ajv-validator/ajv#252]
ajv version: 4.3.0

config:

``` json
{"coerceTypes": true}
```

schema:

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "username": {
      "oneOf": [
        {"type": "string"},
        {"type": "null"}
      ]
    }
  }
}
```

data:

``` json
{"username": null}
```

error:

``` json
[{"keyword":"oneOf","dataPath":".username","schemaPath":"#/properties/username/oneOf","params":{},"message":"should match exactly one schema in oneOf"}]
```

It pass when `{coerceTypes: false}`, so I guess it is a bug

**Comment by epoberezkin** [comment]
Instead of oneOf you probably need to use `"type": ["string", "null"]`.
In your case it works as expected. `null` can be coerced to `"null"` and it also passes `{"type": "null"}`, while oneOf requires only one schema to pass.
In general, coercion increases the probability of passing, so in cases your schema requires that some subschema fails (e.g. inside `oneOf` or `not`) coercion would increase the chances of parent schema failing.

**Comment by foray1010** [comment]
it works!!!! Thanks, it is awesome for making API with

``` js
{
  "coerceTypes": true, // convert type of request params
  "removeAdditional": true // screening response object
}
```

Saved me a lot of work!!!

**Comment by epoberezkin** [comment]
Thank you, that was the use case, also form submissions.
