### ISSUE TITLE
Add assert method

### ISSUE THREAD

**Issue by felixfbecker** [ajv-validator/ajv#274]
Should have the same signature as `validate()`, but instead of returning a boolean, throw an error when the validation failed. This could be used both in APIs (with a custom error handler) and in API tests and would reduce boilerplate code. The error class should be accessible for `instanceof` checks and should have the `errors` property to get details about the failure. The `message` should be set to the return of `errorsText()`.

**Comment by epoberezkin** [comment]
You can extend it like this:

``` javascript
Ajv.prototype.assert = function(schema, data) {
  if (!this.validate(schema, data)) throw new Ajv.ValidationError(this.errors);
};
```

I will think whether it should be a part of the library

**Comment by epoberezkin** [comment]
For tests there is [chai-ajv-json-schema](https://www.npmjs.com/package/chai-ajv-json-schema)

**Comment by broofa** [comment]
Worth revisiting?  Every time I approach this library, it is with the intention of using it in much the same manner as Node's built in `assert()` method.  It would be nice to be able to `compile` a validator that throws rather than returning.  This would be useful, for example, in creating custom sequelize validator functions ...
```
sequelize.define('mymodel', {
  someColumn: {
    ...
    validate: {
      customValidator: ajv.compileAssert({... schema definition ...})
    }
  }
});
```

Also, the suggested workaround (extending `AJV.prototype`) kind of breaks down if you're requiring AJV from multiple files.  You end up with potential race conditions where the file extending AJV has to be required before all other files.

**Comment by epoberezkin** [comment]
@broofa https://github.com/epoberezkin/ajv/blob/master/FAQ.md#can-we-change--extend-api-to-add-a-method-that-would-return-errors-rather-than-assign-them-to-errors-property

Given that it’s convenient to have a wrapper for the library in the application, this would be the place to introduce this API.
