### ISSUE TITLE
defaults don't work inside `anyOf` 

### ISSUE THREAD

**Issue by mbroadst** [ajv-validator/ajv#276]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.4.0, yes

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

``` javascript
{
  ownProperties: true,
  allErrors: true,
  useDefaults: true
}
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

_not_ working:

``` json
{
  "type": "object",
  "properties": {
    "num": { "allOf": [ { "type": "number", "default": 2 }, { "acceptTerms": true } ] }
  },
  "required": [ "num" ]
}
```

working:

``` json
{
  "type": "object",
  "properties": {
    "num": { "type": "number", "default": 2 }
  },
  "required": [ "num" ]
}
```

**Data (please make it as small as posssible to reproduce the issue):**

``` json
{}
```

**Your code (please use `options`, `schema` and `data` as variables):**

``` javascript
let ajv = new Ajv(options);
ajv.addKeyword('acceptTerms', () => () => true);
let validate = ajv.compile(schema);
let valid = validate(data);
if (!valid) {
  console.log(validate.errors);
}
```

**Validation result, data AFTER validation, error messages:**

```
[ { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'num' },
    message: 'should have required property \'num\'' } ]
```

**What results did you expect?**
no errors, the default of `2` would be used

**Do you intend to resolve the issue?**

**Comment by epoberezkin** [comment]
That is the way they are implemented. See [Assigning defaults](https://github.com/epoberezkin/ajv#assigning-defaults):

> default keywords in other cases are ignored:
> - not in properties or items subschemas
> - in schemas inside anyOf, oneOf and not (see #42)
> - in if subschema of v5 switch keyword
> - in schemas generated by custom macro keywords

**Comment by mbroadst** [comment]
Is that just underspecified in the spec? It seems a natural assumption that defaults would apply wherever they are defined

**Comment by epoberezkin** [comment]
`Deafult` is [defined in the spec](http://json-schema.org/latest/json-schema-validation.html#anchor101) as optional, its behaviour is not specified in too much detail.

Taking into account defaults in subschemas of compound keywords inside properties is both difficult to implement and in some cases ambiguous. The existing implementation covers 80%+ of real use cases. If you need multiple defaults depending on the valid schema branch, you just have to use v5 `switch` instead of `anyOf`, because in case of switch it is deterministic and doesn't require a [rollback mechanism](https://github.com/playlyfe/themis#how-it-works).

What is the objection to refactoring the schema in the way that Ajv supports (i.e. putting default keyword on the same level as allOf)?

**Comment by mbroadst** [comment]
Absolutely understandable. Could you expand on the proposed solution at the end there? Maybe I'm just not seeing how to do this in a supported fashion.

**Comment by epoberezkin** [comment]
In your case, this schema would produce the result you want (defaults are assigned before schema is validated):

``` json
{
  "type": "object",
  "properties": {
    "num": {
      "default": 2,
      "allOf": [ { "type": "number" }, { "acceptTerms": true } ]
    }
  },
  "required": [ "num" ]
}
```

Another common use case that would produce confusing results if it were supported is this:

``` json
{
  "type": "object",
  "anyOf": [
    {
      "properties": {
        "type": { "enum": [ "foo" ] },
        "foo": { "type": "integer", "default": 1 }
      },
      "additionalProperties": false
    },
    {
      "properties": {
        "type": { "enum": [ "bar" ] },
        "bar": { "type": "string", "default": "abc" }
      },
      "additionalProperties": false
    }
  ]
}
```

The above wouldn't work without implementing complex rollback logic and that's the reason why defaults inside "anyOf"/"oneOf" (at any depth) are ignored by Ajv.

The same logic can be implemented with this schema:

``` json
{
  "type": "object",
  "switch": [
    {
      "if": { "properties": { "type": { "constant": "foo" } } },
      "then": {
        "properties": {
          "type": {},
          "foo": { "type": "integer", "default": 1 }
        },
        "additionalProperties": false
      }
    },
    {
      "if": { "properties": { "type": { "constant": "bar" } } },
      "then": {
        "properties": {
          "type": {},
          "bar": { "type": "string", "default": "abc" }
        },
        "additionalProperties": false
      }
    },
    { "then": false }
  ]
}
```

The above would assign defaults in the expected way because Ajv knows which branch should be validated based on "if" conditions. Defaults inside "if" schemas are still ignored.

**Comment by kapouer** [comment]
@epoberezkin you should document this (declare default next to anyOf/allOf/oneOf instead of inside), it's a life saver.

**Comment by epoberezkin** [comment]
@kapouer it is in docs here: https://github.com/epoberezkin/ajv#assigning-defaults

**Comment by kapouer** [comment]
I meant the way you use v5 `switch` to have defaults inside "then" schemas applied.

**Comment by epoberezkin** [comment]
@kapouer got it. Will do.
