### ISSUE TITLE
Have a way to disable the extendRefs warning

### ISSUE THREAD

**Issue by miikka** [ajv-validator/ajv#303]
**What version of Ajv you are you using?** 4.7.2
**What problem do you want to solve?** extendRefs warning about issue #260 is quite noisy.
**What do you think is the correct solution to problem?** Add a way to disable it.
**Will you be able to implement it?** Probably.

I'm working with an upstream schema that has $refs extended with additional keywords. I have extendRefs set to `true` and my log is now full of lines like this:

```
$ref: all keywords used in schema at path '.rule[' + i2 + ']' (it will change in the next major version, see issue #260)
```

Right now I'm working around it by setting console.log to a no-op while calling `ajv.compile`, but I'd prefer to have a configuration option to do it.

**Comment by epoberezkin** [comment]
The purpose of the warning is to notify the users that the default behaviour will change in the next major version (in case the option is not specified). In your case, when the option `extendRefs` is explicitly set to `true`, the behaviour won't change so there is no need for the warning.

So we don't need an additional option, we can remove the warning in case the option is set to `true` (and update the message to suggest `{extendRefs: true}` to keep the current behaviour in case the option is `undefined`).

I also noticed that the message contains path expression rather than the actual path (i2 should be replaced with the actual number in the message) - it should be fixed as well.

@miikka PR is appreciated, thank you.

**Comment by epoberezkin** [comment]
in 4.7.7
