### ISSUE TITLE
How to set dataPath to custom validation error?

### ISSUE THREAD

**Issue by xfg** [ajv-validator/ajv#331]
I created custom keyword

``` javascript
ajv.addKeyword('validatePassword', {
  async: true,
  schema: false,
  validate: function (data) {
    return userRepository.findByEmail(data.email)
      .then(user => {
        if (user === null) {
          throw new ajv.ValidationError([{
            dataPath: '.email',
            keyword: 'validatePassword',
            message: 'Неверный email или пароль',
            params: {keyword: 'validatePassword'},
          }]);
        }
        return securityService.validatePassword(data.password, user.password);
      });
  },
  errors: true
});
```

and schema

``` json
{
  "$async": true,
  "type": "object",
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    },
    "password": {
      "type": "string"
    }
  },
  "required": ["email", "password"],
  "validatePassword": true
}
```

now `dataPath` equals to "" but I want that `dataPath` was equal to ".email". How to do this?

**Comment by epoberezkin** [comment]
dataPath is set to the data level where a custom keyword is used, which is an object level rather than property level. In this particular situation the problem is not only email but combination of email and password, which is object (although you may want to differentiate between wrong password and missing user. It is usually considered less secure though and a common practice is to validate password even if user is not found - to prevent timing attacks).

If you need to you can use message or params property in the error object to differentiate errors.

At the moment only [inline keywords](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-inline-compilation-function) allow [defining their own dataPath/schemaPath in errors](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#reporting-errors-in-custom-keywords), because they have information about where in the data (and in the schema) you are. validate/compile keywords don't know which data level they are used in (it can be somewhere deeper in object than root level) so even if they set dataPath it is overwritten to the current dataPath.

**Comment by xfg** [comment]
Thanks for reply. All I want is to display error messages nearby with my input fields. I asked you about this in https://github.com/epoberezkin/ajv/issues/255#issuecomment-243634731 and you suggested me to use `errorDataPath: 'property'`. It work for default ajv keywords but now I don't understand what me do with my own custom keywords.

**Comment by epoberezkin** [comment]
You just need to process your errors in a loop and have some switch inside this loop to attach messages to fields.

**Comment by xfg** [comment]
As a `switch` I wanted to use `dataPath` with `errorDataPath: 'property'`. Maybe example? I don't understand how to solve this task gracefully without crutches.

**Comment by epoberezkin** [comment]
What I meant is that you have to process errors with your own code. dataPath is what it should be, Ajv will not return a different one.

**Comment by xfg** [comment]
You are absolutely right, but to handle errors within my own code I  must know somehow that this error belong to specific object property and if I can't use `dataPath` then I am forced to do it like that

``` javascript
getUserErrors(ajvErrors) {
  return ajvErrors.map(error => {
    if (error.keyword === 'validatePassword') {
      return {field: '.email', message: error.message};
    }
    if (error.keyword === 'otherMyCustomKeyword') {
      return {field: '.otherField', message: error.message};
    }
    ...
    return {field: error.dataPath, message: error.message};
  });
}
```

but it looks like ugly.

If I could set `dataPath` on `Ajv.ValidationError` then all it would have been easier. What are reason why it impossibly do for custom `Ajv.ValidationError` ? Such opportunity has within [tv4](http://geraintluff.github.io/tv4/#definekeyword-keyword-validationfunction-)

> validationFunction is a function that either returns:
> - an error object (containing some of: code/message/**dataPath**/schemaPath)

**Comment by epoberezkin** [comment]
> What are reason why it impossibly do for custom Ajv.ValidationError

The reason is that you don't really know in your custom keyword handler where the keyword is used. `""` simply means root object, but the keyword can be used in some property, e.g.:

``` json
{
  "$async": true,
  "type": "object",
  "properties": {
    "user": {
      "type": "object",
      "required": ["email", "password"],
      "validatePassword": true
    }
  }
}
```

In this case if validatePassword fails dataPath will be ".user".

You can say that you know where in the schema you use the keyword and you can set dataPath as you like. The problem with that approach is that it introduces unnecessary coupling between schema and keyword definition (that, generally speaking, can be used in different places in different schemas).

Also in your case, dataPath will be .email if email property fails validation (type or format).

So yes, you will have to rely on other error object properties to identify errors and attach to fields.

Most likely it will look like:

``` javascript
getUserErrors(ajvErrors) {
  return ajvErrors.map(processError);
});

var KEYWORDS = {
  validatePassword: '.email',
  otherMyCustomKeyword: '.otherField'
};

function processError(error) {
  var field = KEYWORDS[error.keyword] || '';
  return {field: error.dataPath + field,  message: error.message};
}
```

**Comment by xfg** [comment]
Yes I understand you. I just wanted tell that would be nice to give users some variants where they can specify `dataPath` manually (as optional property) if so required by their task or not to specify and then `dataPath` will be generated automaticly by ajv. It doesn't break current api and only gives additional opportunity.

**Comment by epoberezkin** [comment]
Actually, schema compilation context is now passed to "compile" keywords. So it's probably worth supporting option `errors: 'full'` in "compile" keywords as well, so users can define all properties of error objects.

Also dataPath is available in all validation functions, so it is possible to let them set it on some sub-properties of the current data. It would probably require some additional option (like `errors: 'data')? The alternative is to always check if dataPath is already set before setting it.

**Comment by epoberezkin** [comment]
> it's probably worth supporting option errors: 'full' in compiled keywords

It won't work, "compiled" keywords won't be able to set schemaPath in errors, as it is an expression rather then value in the compilation context...
