### ISSUE TITLE
unique property check

### ISSUE THREAD

**Issue by whitemalt** [ajv-validator/ajv#346]
**What version of Ajv you are you using?**
4.9.0
**What problem do you want to solve?**
check property value of object is unique.
**What do you think is the correct solution to problem?**
----
I find this feature in ajv but i'm not found.i found uniqueItem but it doesn't check unique in each property of object. i don't know is already has this feature or not . It good if ajv has this feature 

**Will you be able to implement it?**
not sure but it can check separately
http://stackoverflow.com/questions/30735465/how-can-i-check-if-the-array-of-objects-have-duplicate-property-values

thank you

**Comment by epoberezkin** [comment]
Can you please include your code here that doesn't work as you expect? `uniqueItems` keyword should check for deep equality of objects.

**Comment by whitemalt** [comment]
here i check to "a" property have a unique value

```
var Ajv = require('ajv');
var ajv = new Ajv();
var schema = {
    type: "array",
    uniqueItems: true
}
let data = [{ a: 1 }, { a: 1, b: 2 }, { a: 1, c: 3 }];

var valid = ajv.validate(schema, data);
if (!valid) console.log(ajv.errors);
else console.log('pass');// it say data pass
```
i have work around this case with

```
var Ajv = require('ajv');
var ajv = new Ajv();

var schema = {
    type: "array",
    uniqueItems: true
}
let data = [{ a: 1 }, { a: 1, b: 2 }, { a: 1, c: 3 }];

var valid = ajv.validate(schema, data);
let valueArr = data.map(function (item) { return item.a; });
valid = !valueArr.some(function (item, idx) {
    return valueArr.indexOf(item, idx + 1) !== -1
});
if (!valid) console.log("fail");
else console.log('pass');

```

any idea to use in ajv ?

**Comment by epoberezkin** [comment]
> it says data pass

`uniqueItems` ensures that items are unique, not that the values of individual properties are unique, so the result is correct - items are different.

> i have work around this case with

it can be simplified by applying the same schema you have to both `data` and to `data.map(x => x.a)`

> any idea to use in ajv

Ajv supports [defining custom keywords](https://github.com/epoberezkin/ajv#defining-custom-keywords) in variety of ways. So your validation requirement can be implemented as the keyword `uniqueItemsProperty` where `{"uniqueItemsProperty": "foo"}` would mean that property `foo` value should be unique across all items and `{"uniqueItemsProperty": true}` would mean that all properties should be unique. It will not be included in `ajv` because it implements JSON-Schema spec with some proposals for the future version, rather than arbitrary validation keywords. Feel free to contribute it to `ajv-keywords` package, it can be useful to some people.
