### ISSUE TITLE
Suggestion. Coercing null's only for required properties.

### ISSUE THREAD

**Issue by tsofist** [ajv-validator/ajv#353]
First of all I thank you for your project!

I have a suggestion.
Often coerceTypes behavior is undesirable.
For example
```js
// SH1
var schema = {
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": "number" }
  }
};
var source = { "bar": null };
// Coerce to (current result):
//{ "bar": 0 }
```
It seems to me that it would be logical for such a result:
```js
// Coerce to (desired result):
{  }
```
**since property ```"bar"``` is optional**

Expected (and currently):
```js
// SH2
var schema = {
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": "number" }
  },
  "required": ["bar"]
};
var source = { "bar": null };
// Coerce to (current result):
//{ "bar": 0 }
```

What do you think about it? This is logical and would be very helpful in my case. Possible and other users such behavior would seem preferable.

More example (_problematically_):
```js
// SH3
var schema = {
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": ["number", "null"] }
  }
};
var source = { "bar": null };
// Coerce to:
//{ "bar": null }
```

It may need a separate option?

**Thank you!**

**Comment by epoberezkin** [comment]
`null` is a value in JSON rather than an absent property. So if you use an option `coerceType` it will be coerced to the first allowed type (if "null" is not allowed)

The last schema does not coerce `null` to `0`, it leaves it as it is (see https://runkit.com/esp/583dc2ae82382300136c0c3a). What is the problem here?

The behaviour you want for required property (2nd schema) should be achieved with the `default` keyword - when the property is missing there is nothing to coerce but if the default is present it will be used. See docs about assigning defaults.

I don't think any changes are necessary to be honest. You can also add any custom post-processing with custom keywords (e.g. if you want to delete property when it is `null` or `0`).

**Comment by tsofist** [comment]
- I sealed in SH3, sorry
- SH2 - is the current behavior with a required property
- Desired result of SH1 - empty source, because this property is not necessary, it can not contain null seamlessly and can be removed from the source (by new special coercive option)

**Comment by epoberezkin** [comment]
> Desired result of SH1 - empty source, because this property is not necessary, it can not contain null seamlessly and can be removed from the source (by new special coercive option)

I will not be adding an additional option, because:
- I think this requirement is not common enough
- coerce means "change", it does not mean "remove". `null` is a value, so removing it is not something Ajv will support.
- making coercion dependent on another keyword in addition to `type` keyword will substantially complicate it.

It can be implemented for your use-case as a [custom keyword](https://github.com/epoberezkin/ajv#defining-custom-keywords), e.g. `removeNull: true` or you can even implement a more generic keyword `removeIf: { type: 'null' }` that takes schema as a value and removes current property if the data is valid against this schema. I'd be happy to add it to [ajv-keywords](https://github.com/epoberezkin/ajv-keywords) package if you contribute it there.

**Comment by tsofist** [comment]
@epoberezkin thanks for your reply!

**Comment by Reggino** [comment]
Thanks for this, it gives a lot of context to an issue i am experiencing right now.

@epoberezkin i would like this behaviour in all validations on all my schemas and nested schemas. Is it in some way possible to use a (single) custom keyword for global ajv validation behaviour?

**Comment by epoberezkin** [comment]
> i would like this behaviour in all validations on all my schemas and nested schemas.

Why do you need it to be a part of validation then? The whole point of schema is to apply schema-specific requirements (and possibly changes). If you just want to modify everything, it can be just the code you run before or after validation.
