### ISSUE TITLE
Validation works incorrectly if the fragment of a remote $ref is missing "type" property.

### ISSUE THREAD

**Issue by daditto** [ajv-validator/ajv#439]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
4.11.5

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
{}

```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```javascript
let dataSchema = {
    properties: {},
    searchProperties: {
        // type: 'object',
        properties: {
            value: { type: 'integer' }
        }
    }
};

let responseSchema = {
    properties: {
        data: {
            oneOf: [{
                $ref: 'data-schema#/searchProperties'
            }, {
                type: 'string'
            }]
        }
    }
}
```

**Data (please make it as small as possible to reproduce the issue):**

```json
{ "data": "546" }

```

**Your code (please use `options`, `schema` and `data` as variables):**

```javascript
'use strict';

const ajv = require('ajv');
const validator = new ajv({});

let dataSchema = {
    properties: {},
    searchProperties: {
        // type: 'object',
        properties: {
            value: { type: 'integer' }
        }
    }
};

let responseSchema = {
    properties: {
        data: {
            oneOf: [{
                $ref: 'data-schema#/searchProperties'
            }, {
                type: 'string'
            }]
        }
    }
}

validator.addSchema(dataSchema, 'data-schema');

let responseData = { data: '546' };

let isValid = validator.validate(responseSchema, responseData);

console.log(isValid);
console.log(validator.errors);

```

**Validation result, data AFTER validation, error messages:**

```
false
[ { keyword: 'oneOf',
    dataPath: '.data',
    schemaPath: '#/properties/data/oneOf',
    params: {},
    message: 'should match exactly one schema in oneOf' } ]

```

**What results did you expect?**
```
true
null
```
It is worth noting that if I uncomment the `type: "object"` in the data schema, it magically works.

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment]
@daditto The result is correct. the absence of "type" keyword (the one that is commented out) makes the data valid against both subschemas inside "oneOf", because "properties" keyword does not require data to be an object, it only applies IF the data is an object. And the data is only valid if it is valid against one and only one subschema inside  "oneOf" keyword.

This is all according to specification.

Please see [the docs on validation keywords](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md) for more details about how they work.
