### ISSUE TITLE
Document plugin convention

### ISSUE THREAD

**Issue by jdthorpe** [ajv-validator/ajv#524]
Given that AJV is wonderfully extensible, it's natural to bundle keywords into a NPM module and there are plenty of them out there, with a variety of very similar API's which look like one of these:

    // CREATE AN INSTANCE
    var Ajv = requrire('ajv");
    var ajv = new Ajv();

    // IMPORT THE PLUGIN MODULE
    var my_plugin = require("some-plugin-module");

    // ADD THE KEYWORDS TO THE INSTANCE
    my_plugin(ajv,{options}) 
    // OR 
    my_plugin.add_keywords(ajv,option1=a,option2=b)
    // OR 
    my_plugin({ajv,option1,option2})
    // OR 
    for(k in Object.keys(my_plugin)){
       ajv.addkeyword(my_plugin[k])
    } 
    // etc.

All the plugin's essentially do the same thing:  (1) provide an `Ajv` instance, and (2) provide some parameters (typically an object).  However inconsistency of the API's makes parameterizing the set of plugins to be included on an instance require a bit of manual coding and is difficult to offload onto a text parameter file.

For the sake of consistency across the AJV plugin ecosystem, it would be nice to have a method on Ajv instances that standardizes how plugins are added, which could be as simple as:

    function(plugin,options){
         plugin(this,options)
    }

which would be called like so:

    ajv.plugin(require("some-plugin-module"), {"my":"preferences"})

which would encourage developers to adopt a consistent API for their AJV add-in modules.

------------------------------------
Full Disclosure: having plugins that are compatible with [ajvpy](https://github.com/jdthorpe/ajvpy#plugin-modules) is part of my motivation, and this may be a trip down the rabbit hole, but here's how I load my own plugins in NodeJS:

    var semver = require("semver");
    var Ajv = require("ajv");
    var ajv = new Ajv();

    var plugin_spec = { // easily offloaded to a JSON File
        "ajv-data-table": {
            "version": "^1.0.0",
            "options": {
                "foo": "bar"
            }
        },
        "ajv-currency": {
            "version": "^3.4.5",
            "options": {
                "foo": "bar"
            }
        }
    }
    add_plugins(ajv,plugin_spec)

    function add_plugins(/* an AJV Instance */ajv,
                         /* plugin options  */plugins){
        for(key in plugins){
            if(!plugins.hasOwnProperty(key))
                continue;
            
            if(plugins[key].version){
                var version = require(key+"/package.json").version;
                if(!semver.satisfies(version, plugins[key].version))
                    throw new Error(`Installed version "${version}" of plugin "${key}" does not satisify "${plugins[key].version}"`);
            }

            if(plugins[key].options){
                require(key)(ajv,plugins[key].options)
            }else{
                require(key)(ajv)
            }
        }
             
    }

**Comment by epoberezkin** [comment]
Hi @jdthorpe.

At the moment all my and your plugins seem to have the same api - they export a function that accepts ajv instance, with an optional second argument (parameters), and returns the same ajv instance so you can chain them.

I am reluctant to change it for this reason (several existing plugins), and also because I don't want ajv to be in any way responsible for the plugins as they could potentially conflict each other, require a certain loading order etc.

Maybe instead of introducing an ajv method, it's better to

1) document the current convention as a standard (a simple README change),
2) optionally provide some [command-line] plugin tester that would check that
  - the package exports a function
  - ajv instance can be passed to it and it doesn't throw
  - the same ajv instance is returned
  - possibly, the function signature has only 1 or 2 arguments

What do you think?
If that's agreeable, a PR is welcome.

Thank you.

**Comment by epoberezkin** [comment]
The second part should probably go into ajv-cli, as it already supports such plugins (without support for parameters though).

**Comment by epoberezkin** [comment]
Added https://github.com/jessedc/ajv-cli/issues/41

**Comment by epoberezkin** [comment]
in [6.0.0-beta.0](https://github.com/epoberezkin/ajv/releases/tag/v6.0.0-beta.0)
