### ISSUE TITLE
Is there a built-in api to convert the schema with $data reference

### ISSUE THREAD

**Issue by Airkro** [ajv-validator/ajv#537]
like:

```js
const schema = {
  type: 'object',
  properties: {
    test: {
      type: 'number'
    },
    target: {
      type: 'number'
      minimum: { $data: '/test' }
    }
  }
};

const data = {  test: 5 };

func(schema, data);
// output:

{
  type: 'object',
  properties: {
    test: {
      type: 'number'
    },
    target: {
      type: 'number'
      minimum: 5
    }
  }
}

```

Thanks

**Comment by epoberezkin** [comment]
@Airkro no, ajv doesn't transform schemas, the compiled validation function uses actual runtime data - it would have been very inefficient otherwise if the schema needed to be re-compiled every time.

If you need to do schema transformation like you describe you can use json-schema-traverse package to iterate through all the subschemas and replace $data reference in all the keywords.
