### ISSUE TITLE
Improve uniqueItems algorithm for scalars of the same type

### ISSUE THREAD

**Issue by mtalonen** [ajv-validator/ajv#608]
Unique items check uses inefficient algorithm with two nested for loops. I have 20k lines schema and I am validating array with 60000 entries.

**Comment by mattbrunetti** [comment]
What algorithm would you suggest? This project is in ES5, so you can't use `Array.prototype.includes`. I'm not sure how two nested `for` loops can be avoided.

**Comment by mattbrunetti** [comment]
@mtalonen Where is that code?

**Comment by epoberezkin** [comment]
Single pass in general case requires hashing objects to strings using stable-stringify and it is slower - I tried.

It is possible to prescan an array and choose hashing in case all values are the scalars of the same type.

I don't mind to allow passing a function via uniqueItems option (passing false now disables uniqueItems entirely) - this function would accept an array and implement any other algorithm (comparing by hashing or by reference using a faster indexOf instead of the second loop). Or maybe compilation can be a bit more intelligent and use hash in case there it "type": "number/string/boolean/null" in the schema (but it would have to ignore items that are of different type to avoid extra errors in case allErrors: true is used).

**Comment by epoberezkin** [comment]
> Where is that code?

https://github.com/epoberezkin/ajv/blob/master/lib/dot/uniqueItems.jst#L17

**Comment by mtalonen** [comment]
I'm referencing to uniqueItems.jst file. Here's inefficient part:

```
var {{=$valid}} = true;
  if ({{=$data}}.length > 1) {
    var i = {{=$data}}.length, j;
    outer:
    for (;i--;) {
      for (j = i; j--;) {
        if (equal({{=$data}}[i], {{=$data}}[j])) {
          {{=$valid}} = false;
          break outer;
        }
      }
    }
  }
```

If we used sort before check, we could compare two consecutive values (just a draft):

```
  var {{=$valid}} = true;
  if ({{=$data}}.length > 1) {
    var foo = {{=$data}}.sort();
    var j;
    outer:
    for (var i=0;i<foo.length-1;i++) {
        if (equal(foo[i], foo[i+1])) {
          {{=$valid}} = false;
          break outer;
        }
    }
  }
```

**Comment by epoberezkin** [comment]
Items can be objects, you can't sort them in general case - see my comment above. For same-type scalars you can use hash - it's more efficient than sorting (and you can't sort the original data).

**Comment by epoberezkin** [comment]
in [6.0.0-beta.0](https://github.com/epoberezkin/ajv/releases/tag/v6.0.0-beta.0)
