### ISSUE TITLE
"$async": true should persist consistently through $refs (?)

### ISSUE THREAD

**Issue by markchart** [ajv-validator/ajv#647]
version: ajv@6.0.0-rc.1 plus ajv-async@beta

```javascript
var ajv_options = {
    allErrors: false,
    verbose: true,
    useDefaults: true,
    jsonPointers: true,
    async: true
};

```

When I define async custom keyword xxx_fetch (which works fine)
the schema below provokes this error:

```code
...\ajv\lib\dotjs\validate.js:94
    if ($async && !it.async) throw new Error('async schema in sync schema');

Error: async schema in sync schema

    at Object.generate_validate [as validate] (...\node_modules\ajv\lib\dotjs\validate.js:94:36)
    at Object.generate_ref [as code] (...\node_modules\ajv\lib\dotjs\ref.js:70:22)
    at Object.generate_validate [as validate] (...\node_modules\ajv\lib\dotjs\validate.js:261:37)
    at Object.generate_properties [as code] (...\node_modules\ajv\lib\dotjs\properties.js:188:26)
    at generate_validate (...\node_modules\ajv\lib\dotjs\validate.js:334:35)
    at Ajv.localCompile (...\node_modules\ajv\lib\compile\index.js:86:22)
    at Ajv.resolve (...\node_modules\ajv\lib\compile\resolve.js:54:19)
    at Object.resolveRef (...\node_modules\ajv\lib\compile\index.js:187:21)
    at Object.generate_ref [as code] (...\node_modules\ajv\lib\dotjs\ref.js:21:22)
    at Object.generate_validate [as validate] (...\node_modules\ajv\lib\dotjs\validate.js:261:37)
```

**JSON Schema**

```json
{
    "$async": true,
    "properties": {
        "foo": { "$ref": "#/definitions/Foo" }
    },
    "definitions": {
        "Foo": {
            "properties": {
                "bar": { "$ref": "#/definitions/Bar" }
            }
        },
        "Bar": {
            "properties": {
                "blitz": {
                    "xxx_fetch": "string"
                }
            }
        }
    }
}

```

Adding "$async": true to "Bar" does _not_ help

```json
{
    "$async": true,
    "properties": {
        "foo": { "$ref": "#/definitions/Foo" }
    },
    "definitions": {
        "Foo": {
            "properties": {
                "bar": { "$ref": "#/definitions/Bar" }
            }
        },
        "Bar": {
            "$async": true,      //_DOES_NOT_HELP
            "properties": {
                "blitz": {
                    "xxx_fetch": "string"
                }
            }
        }
    }
}

```
but adding $async to Foo _does_ help
```json
{
    "$async": true,
    "properties": {
        "foo": { "$ref": "#/definitions/Foo" }
    },
    "definitions": {
        "Foo": {
            "$async": true,      //_FIXES_THE_PROBLEM_(note_no_$async_in_'Bar')
            "properties": {
                "bar": { "$ref": "#/definitions/Bar" }
            }
        },
        "Bar": {
            "properties": {
                "blitz": {
                    "xxx_fetch": "string"
                }
            }
        }
    }
}

```

It takes _two_ levels of $ref to lose track of $async.
The following does NOT cause an error:
```json
{
    "$async": true,
    "properties": {
        "foo": { "$ref": "#/definitions/Bar" }  //_'SKIPPING'_Foo_AVERTS_Async_ERROR
    },
    "definitions": {
        "Foo": {
            "properties": {
                "bar": { "$ref": "#/definitions/Bar" }
            }
        },
        "Bar": {
            "properties": {
                "blitz": {
                    "xxx_fetch": "string"
                }
            }
        }
    }
}

```

My first thought is that once $async=true is set, it should
remain in effect until explicitly disabled.  At least for references
to "#/definitions" in the same object, yes?

Second thought is that putting "$async": true into "leaf"
portion of schema ought to avert error, but doesn't.

Is there any way I can avoid decorating every portion of
my schema that might be part of a chain of $ref's with
"$async": true ?

Thanks much for any advice!

(I confess I don't actually understand why "$async" is a schema
keyword (custom to ajv) at all.  Why isn't $async just an option
to Ajv or ajv.compile?)

**Comment by epoberezkin** [comment]
>  I don't actually understand why "$async" is a schema
keyword (custom to ajv) at all. Why isn't $async just an option
to Ajv or ajv.compile?

Just one of possible design decisions, seems to be the most flexible. If you make it an instance option, then all schemas would be compiled to async functions. If you make it an option of compile (or actually introduce any compilation options) it becomes much more difficult to cache schemas as options should become part of the cache key - there is an abandoned branch with this idea.

Docs say that all referenced schemas should have their own $async: true if they are asynchronous. The reason why it works for a single reference (and it probably shouldn’t) is because ref without refs is inlined by default and the keyword is processed in the context of async function. If you use option inlineRefs: false I expect the compilation to fail.

The option $async: true to enforce async mode on all schemas was recently proposed, I decided not to implement it.

Given that asynchronous validation is very unlikely to be ever standardised I think it’s not a bad thing to require $async: true on all schemas in the chain - it makes it explicit and expected.

**Comment by markchart** [comment]
Thanks for explaining.  I agree that "asynchronous validation"
is unlikely to be standardized, but I suspect that is because
most JSON Schema users would find the term meaningless.

In **ajv** the "$async" schema keyword is the only one* that has
nothing to do with the data in the JSON document to be
validated.  That _data_ is never more or less "asynchronous."
All of the other keywords, including custom keywords (or
formats) that I define, help test or affect that JSON data.
(*Well, the only one I've run into so far.)

I want to do I/O in the context of validation with a custom
keyword (every dev comes to this sooner or later).  Thanks to
the !^?*% excellent design of the Javascript platform, I must
go async.  But that has nothing to do with the structure of
the data I want to specify and validate.  For me, adding a
custom keyword means I must run **ajv** in async mode just
so my custom keyword will work-- I certainly don't want to
turn asyncness on and off in sub-schemas when I use $ref
to make my overall schema easier to build and maintain--
I use my custom keyword(s) throughout.

I grok that "asyncness" is a serious implementation/run-time
consideration for **ajv**, and **ajv** reads schemas so there is a
strong case for controlling **ajv**'s behaviour with special
keywords in those schemas.  Then it is convenient to refer to
"asynchronous schemas" when talking about **ajv**.  But with
respect to the data, I fear that term is not useful.

Just for today I apply this code after I read a schema file:
```javascript
// read in schema from external storage, then...
schema["$async"] = true;
if (schema.hasOwnProperty("definitions")) {
    var defs = Object.keys(schema.definitions);
    for (var x = 0; x < defs.length; x++) {
        schema.definitions[defs[x]]["$async"] = true;
    }
}
```
That works for the moment, but obviously if I begin
to allow more general use of $ref my $async-schema-
patching code will become ugly.

I do not much like this approach, but my other choice
is to tell people writing extensions to my product to
decorate all of their schemas with "$async": true just
so the validator won't choke.

(There's also the "come from" problem-- since $ref
could refer to even a tiny portion of schema, it seems
like every property in every schema given to **ajv**
might need a prophylactic "$async": true in case it
ends up in a $ref chain.)

**Comment by markchart** [comment]
The more I think about this, the more problematic "$async" seems.
Suppose I define a schema like:
```json
{
    "$async": true,
    "properties": {
        "p": {
            "properties": { "blah": "blah" },
            "additionalProperties": { "$ref": "#/definitions/a" }
        },
        "q": {
            "properties": { "yada": "yada" },
            "additionalProperties": { "$ref": "#/definitions/b" }
        }
    },
    "definitions": {
        "a": { "$async": true, "properties": { "foo": { "custom_keyword": "bar" } } },
        "b": { "$async": true, "properties": { "whatever": "whatever" } }
    }
}
```

Everything works until someone tries to add another
property extending the schema of one defined earlier
by reference:
```json
{
    "$async": true,
    "properties": {
        "p": {
            "properties": { "blah": "blah" },
            "additionalProperties": { "$ref": "#/definitions/a" }
        },
        "q": {
            "properties": { "yada": "yada" },
            "additionalProperties": { "$ref": "#/definitions/b" }
        },
        "x": {
            "properties": { "new": "xxx" },
            "if": true,
            "then": { "$ref": "#/properties/p" }
        }
    },
    "definitions": {
        "a": { "$async": true, "properties": { "foo": { "custom_keyword": "bar" } } },
        "b": { "$async": true, "properties": { "whatever": "whatever" } }
    }
}
```
**Boom!**
```code
...\ajv\lib\dotjs\validate.js:94
    if ($async && !it.async) throw new Error('async schema in sync schema');

Error: async schema in sync schema
```
(If my example is slightly incorrect I apologize, I am pretty
sure the basic problem exists.)

The only way to avert the crash is to put "$async": true into
nearly every property, because someone might $ref to it in
the future.

That seems a bit awkward to me, considering that "$async"
isn't doing any work with respect to the data, only telling
**ajv** not to blow up mysteriously.

**Comment by epoberezkin** [comment]
> The more I think about this, the more problematic "$async" seems.

That looks similar to complaining about the need to use "async" keyword together with JS function when it uses "await". Couldn't JavaScript figure out without it that the function is "async"? Probably it could, but because this function behaves very differently from normal functions it is better to have them explicitly marked as something else. My arguments for using this approach were similar - async schemas behave quite differently so they should be marked both to simplify their compilation and to make it clear to the users. And given that $ref is very similar to a function call, if you $ref to some subschema that uses async keywords that subschema should be marked as $async.

> The only way to avert the crash is to put "$async": true into
nearly every property, because someone might $ref to it in
the future.

Only in those that use async keywords really.

> That seems a bit awkward to me, considering that "$async"
isn't doing any work with respect to the data

There are standard keywords that have nothing to do with the data and instead define how the schema should be processed - $schema, $id, $ref. The idea for $async was similar.

So I am afraid I do not plan to change this approach.
