### ISSUE TITLE
Avoid RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gpietro** [ajv-validator/ajv#660]
Let's say I have 150 schemas that I need to use for input validation of my application.
I did try with asyncCompile but it doesn't work.
addSchema method doesn't compile the added schemas.
There is a way to precompile all my 150 schemas before validating and avoid Maximum call stack error?

**Comment by epoberezkin** [comment]
> I did try with asyncCompile but it doesn't work.

You may file a separate issue on that, not sure why it didn't work, but some details would help.

> addSchema method doesn't compile the added schemas.

They are compiled when you call compile or getSchema method. Not compiling when addSchema is called allows to add them in any order (and also mutual recursion).

> There is a way to precompile all my 150 schemas before validating and avoid Maximum call stack error?

I doubt the Maximum call stack error is caused by the number of schemas, more likely it is caused by infinite recursion in schema definition for the same location in data instance: either you have schema that is similar to `{$ref: '#'}` or to schemas referencing each other at the same location in data.

Do they all use each other so they cannot be compiled separately? Please make a minimal example to reproduce the issue.

When you file an issue, can you please use the template?
