### ISSUE TITLE
Request: Smaller node_modules installed size

### ISSUE THREAD

**Issue by max-mapper** [ajv-validator/ajv#680]
**What version of Ajv you are you using?**

6.0.1

**What problem do you want to solve?**

ajv appeared in my application because i use request, and request uses har-validator which uses this now. I was hunting down large modules in my application and ajv was one of the largest, with an installed footprint of 1.2MB. I looked at other json validators mentioned in the ajv readme and their installed size on disk were all around ~350kb (is-my-json-valid, djv, json-schema-validator-generator).

**What do you think is the correct solution to problem?**

As I am distributing my application as a bundled node executable using `pkg`, it would be nice if this module was under or around 350kb to be in line with the alternatives in terms of disk space.

**Will you be able to implement it?**

Not at this time

**Comment by epoberezkin** [comment]
Half of the size are bundles that have to be in npm for cdnjs to work... Maybe with https://github.com/epoberezkin/ajv/pull/669 it can be changed.

**Comment by scriptjs** [comment]
Hi Max @maxogden, have you tried pre-compiling your schema with the ajv cli and just including the compiled validate method. I hear what you're saying about the size. This had me concerned as well but this worked well for me for small bundles. You can write a script for your package.json to generate the code to include in your package. You still get access to the schema with `validate.schema` This is analogous to what @mafintosh did with protocol buffers by including the generated code instead of the entire validation lib. Check it out at https://github.com/jessedc/ajv-cli

**Comment by carlnordenfelt** [comment]
I see that #669 has been merged since quite a while back.
What are the plans to remove `dist` from the npm package?

As can be seen from the following commands, `dist` makes up for abut half the size of the package

```
$ pwd
>/.../node_modules/ajv

$ du -h
> 528K	./dist
> 28K	./scripts
> 140K	./lib/dot
>  64K	./lib/compile
>  32K	./lib/refs
> 180K	./lib/dotjs
> 464K	./lib
> 1.1M	.

$ grep "version" package.json 
>  "version": "6.10.2"
```

**Comment by epoberezkin** [comment]
@carlnordenfelt TODO list is tracked here: #940

And it is blocked by https://github.com/cdnjs/cdnjs/pull/13316

I will close this issue as it now seems the same as #940

**Comment by epoberezkin** [comment]
I looked if ./lib/dot can be removed, but it is used by some keywords in ajv-keywords (and may be used by other users who define their custom keyword), so it will have to stay.
