### ISSUE TITLE
Bug: custom formats work wrong in v6.1.1

### ISSUE THREAD

**Issue by droganov** [ajv-validator/ajv#697]
Testcase:

```
var formats = {
  positiveIntegerFormat: /^[0-9]*$/,
};
var options = {
  allErrors: true,
  errorDataPath: 'property',
  format: 'full',
  formats: formats,
  useDefaults: true,
  v5: true,
};

var schema = {
    type: 'object',
    properties: {
      maxFundsInDollars: {
        format: 'positiveIntegerFormat',
        type: 'number',
        default: null,
        minimum: 0,
        maximum: 10,
      },
    },
    required: ['maxFundsInDollars'],
  };

var object = { maxFundsInDollars: 2.1 };
var ajv = Ajv(options);
var validate = ajv.compile(schema);
var valid = validate(object);

console.log('ajv:', valid);
console.log('regex:', formats.positiveIntegerFormat.test(object.maxFundsInDollars));
```

expected output:
```
"ajv:" false
"regex:" false
```

Testcase output:
```
"ajv:" true
"regex:" false
```

**Comment by droganov** [comment]
I've found `integer` type in docs, which lowers the severity, but it's still strange to me, why same expression works differently.

**Comment by M-TGH** [comment]
~~Hey, it seems the format validation is only used on string types as per [this part in the readme](https://github.com/epoberezkin/ajv#validation-keywords).~~
EDIT: Statement was invalid, seems this README.md part is old/unupdated, see newer comment.

As per whether this should or shouldn't be the case, I'm not sure what AJV's owner his opinion on the matter is but the JSON-schema spec is a bit vague, see: [this part of their docs on format](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.1)

> A format attribute can generally only validate a given set of instance types. If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed.

But on the topic of a solution:

It looks to me like using the type "integer" would result in what you're trying to achieve (like you mentioned in your comment). Far as keeping it positive just keep the minimum on 0 (as per what you already have).

Or does this just truncate numbers with decimals to ones without decimals? If so I guess it would assert to false when just using number and setting the ["multipleOf"](https://github.com/epoberezkin/ajv#validation-keywords) keyword to 1.

**Comment by M-TGH** [comment]
It seems the above mentioned part of the README.md is missing that format can be applied to integer.

When further looking into formats I noticed that in the [addFormat](https://github.com/epoberezkin/ajv#addformatstring-name-stringregexpfunctionobject-format---ajv) function used you can specify the type you want your format to be able to apply to ("string" or "number", other things not supported). 

Hence changing your formats object around a bit might work: 

```
var formats = {
  positiveIntegerFormat: {
    validate: /^[0-9]*$/,
    type: 'number',
  },
};
```

I haven't tested wether AJV will test numbers through regex however, although since JS supports it it shouldn't be a problem. In case AJV doesn't you might have to change validate to a function that does the check instead.

**Comment by epoberezkin** [comment]
That is correct. Regexp with numbers may work, not sure, it wasn’t tested.
