### ISSUE TITLE
Feature request: type-aware validation functions

### ISSUE THREAD

**Issue by dcolthorp** [ajv-validator/ajv#736]
**What version of Ajv you are you using?**
6.2.1

**What problem do you want to solve?**
Make better use of TypeScript types with AJV. 

We're using [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) to generate typescript types from our JSON schemas. To use these, we're currently creating [type guard](https://basarat.gitbooks.io/typescript/docs/types/typeGuard.html) functions that use the schema to validate a value as an unknown shape. If the schema validates, we know that the typescript type is accurate. Right now this is a manual process, because AJV doesn't provide a mechanism to tie a typescript type to a ValidateFunction when compiling a schema.

**What do you think is the correct solution to problem?**

Provide a way to `compile<SomeType>(mySomeTypeSchema)` which returns a `ValidateFunction<T>`, which might look something like `(data: any,...) => data is T`. Using this validate function in an if statement would then let TypeScript automatically cast `data` to `T` within the then branch without an explicit cast.

This might look something like

1. Change `ValidateFunction` to `ValidateFunction<T=any>` and the return type to `data is T`
2. Change `compile` and other functions that return `ValidateFunction` to e.g. `compile<T=any>(schema: object | boolean): ValidateFunction<T>`;

The complication is the return type of `data is T | Thenable<any>`. Since TypeScript doesn't know which you have statically, this doesn't get you all the way there. It does work if you remove the `Thenable<any>` return type option. Solving this will require either a more nuanced modelling of the types – perhaps dividing `ValidateFunction` from `AsyncValidateFunction` or providing a few overloads for `ValidateFunction` may solve it, though I admit I haven't looked that closely enough to know for sure.

**Will you be able to implement it?**

I'd be happy to help translate example use cases in to type signatures. Time to get deep enough familiarity with AJV is the main limiting factor to putting making the changes entirely myself.

**Comment by dcolthorp** [comment]
If it's helpful (or anyone else is interested), here's what we're doing to work around this issue currently:

```ts
export function buildValidator<T>(ref: string): ValidateFunction<T> {
  // we previously used `addSchema` to define `my-schema.json`
  return ajv.compile({
    $ref: `my-schema.json#/definitions/${ref}`
  });
}
export interface ValidateFunction<T> extends Ajv.ValidateFunction {
  _t?: T; // stop linter from complaining about unused T variable
}
function isValid<T>(
  validator: ValidateFunction<T>,
  candidate: any
): candidate is T {
  return validator(candidate) === true;
}

const validateFoo = buildValidator<{foo: number}>("asdf");
const y: any = {};
if(isValid(validateFoo, y) {
  y // is treated as a `{foo: number}` here.
}
```

**Comment by epoberezkin** [comment]
Just to clarify, you want generated code to be typescript?

**Comment by epoberezkin** [comment]
Probably not...

**Comment by dcolthorp** [comment]
Hi @epoberezkin,

I'm not looking for AJV to generate types or for any change to the run-time behavior of AJV or even the existing TypeScript API. I'm hoping we can enhance AJV's built-in typescript types to enable users opt into better leveraging AJV as a way to generate type testing functions, which is ultimately what JSON schema is all about.

TypeScript supports a few features that are particularly relevant here:

1. [Type Guards](https://basarat.gitbooks.io/typescript/docs/types/typeGuard.html) enable users to encode in the type of a function that it is a predicate that proves a value is a valid instance of some type. I'd like a way to invoke AJV which returns a validation function which is a type guard for a type which I provide. (The `data is T` bit from my example `compile` type signature above)
2. A [generic](https://basarat.gitbooks.io/typescript/docs/types/generics.html) type definition for AJV would let users pass in a TypeScript type that corresponds to their schema at the time the schema is compiled, and TypeScript would henceforth know that that particular AJV validation function is a validator for the specified type. (`ValidationFunction<T>` above)
3. A [generic parameter default](https://blog.mariusschulz.com/2017/06/02/typescript-2-3-generic-parameter-defaults) is one way we might be able to introduce this change without breaking the API for users who are not providing a TypeScript type. Another option may be providing an [overload](http://www.typescriptlang.org/docs/handbook/functions.html#overloads).

The two changes I suggested in my original message in this issue show an example of how that could be structured.

With those changes, I'd expect to be able to do the following:

```ts
const isPerson = ajv.compile<Person>("person.schema.json");
// isPerson is a type guard that proves it's argument is a Person.
// The return type of isPerson(data) is `data is Person`

if (isPerson(someData)) {
  // TypeScript type checks `someData` as a `Person` in this block
  alert(`${someData.firstName} ${someData.lastName}`);
} else {
 // TypeScript knows that `someData` is _not_ a person in this block;
}
```

I believe these changes can be made a) without breaking the current TypeScript API, b) without changing any runtime behavior in AJV, and c) without adding additional machinery to e.g. generate types. This change is merely about better modeling the existing behavior of AJV with TypeScript's type system.

It's worth noting that there's nothing stopping users from inventing this machinery themselves. The workaround I posted in my follow-up message provides all of the same capabilities. However, this does seem like it should be a part of AJV, as the primary reason for using AJV is to check that data matches the set of contstraints for some type, so they can know they have a valid instance of that type. This is exactly what a type guard in TypeScript are for, so this seems like a more natural way to model validation functions in TypeScript.

Does this clarify the nature of the request? I'm happy to provide additional clarification as necessary.

Also, do you have concerns about making such a change? From my outside perspective, it seems like a win for users that is in the spirit of what AJV is already designed to do, but perhaps there are potential concerns I haven't considered.

**Comment by epoberezkin** [comment]
Looks like it won’t hurt... cc @blakeembrey

**Comment by blakeembrey** [comment]
@epoberezkin This should be good and all the parts were well documented above by @dcolthorp 👍 (just needs the generic param and default it to `= any`). I tend to have done this myself in the past by wrapping a function like `const x = (x: any): x is Person => validate(x)`.

**Comment by AndrewO** [comment]
I had this exact idea yesterday, so I'm glad I checked the issues first and found this. I agree with @dcolthorp that this seems like something that should be able to be done with no runtime changes or additional layers. But so far, I've been a bit confounded by the existing return type of `ValidationFunction`. I haven't found a good way of making it act as a type guard when called one way or a `Promise` returning function in another.

Another complication is that, as I read [this](https://github.com/Microsoft/TypeScript/issues/5951#issuecomment-162276495) at least, type guards need to be on the function declaration proper, and not just on the type definition due to the fact that they're contextually typed. I'm wondering if this is just a matter of generating some JSDoc or commented type annotations in the compiled function? That would be a slight runtime change, but I don't think it would be noticeable.

[Here's a TypeScript Playground link](https://www.typescriptlang.org/play/index.html#src=%2F%2F%201.%20Simple%2C%20works%20with%20type%20assertions%20on%20the%20validation%20functions.%0D%0A%2F%2F%20interface%20Validator1%3CT%3Dany%3E%20%7B%20(data%3A%20any)%3A%20data%20is%20T%3B%20%7D%0D%0Atype%20Validator1%3CT%3Dany%3E%20%3D%20(data%3A%20any)%20%3D%3E%20data%20is%20T%3B%0D%0A%2F%2F%20...%20but%20it%20breaks%20when%20we%20add%20the%20union%20to%20the%20return%20type%0D%0A%2F%2F%20type%20Validator1%3CT%3Dany%3E%20%3D%20(data%3A%20any)%20%3D%3E%20data%20is%20T%20%7C%20Promise%3CT%3E%3B%0D%0A%2F%2F%20const%20isStringBool%20%3D%20%3CValidator1%3E((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22)%3B%0D%0A%2F%2F%20const%20isString%20%3D%20%3CValidator1%3Cstring%3E%3E((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22)%3B%0D%0A%0D%0A%2F%2F%202.%20So%20async%20is%20an%20issue%20above.%20This%20won't%20compile%20because%20they%20must%20have%20identical%20type%20parameters.%0D%0A%2F%2F%20type%20Validator2%3CT%3E%20%3D%20(data%3A%20any)%20%3D%3E%20data%20is%20T%3B%0D%0A%2F%2F%20type%20Validator2%20%3D%20(data%3A%20any)%20%3D%3E%20boolean%20%7C%20Promise%3Cany%3E%3B%0D%0A%0D%0A%2F%2F%203.%20How%20about%20conditional%20types%3F%0D%0Atype%20Validator3%3CT%3Dvoid%3E%20%3D%0D%0A%20%20%20%20T%20extends%20void%20%3F%20(data%3A%20any)%20%3D%3E%20boolean%20%3A%0D%0A%20%20%20%20(data%3A%20any)%20%3D%3E%20data%20is%20T%3B%0D%0A%2F%2F%20const%20isStringBool%20%3D%20%3CValidator3%3E((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22)%3B%0D%0A%2F%2F%20const%20isString%20%3D%20%3CValidator3%3Cstring%3E%3E((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22)%3B%0D%0A%0D%0A%2F%2F%204.%20Looks%20good.%20Let's%20add%20async.%0D%0Atype%20Validator4%3CT%3Dvoid%3E%20%3D%0D%0A%20%20%20%20T%20extends%20void%20%3F%20(data%3A%20any)%20%3D%3E%20boolean%20%3A%0D%0A%20%20%20%20T%20extends%20Promise%3Cany%3E%20%3F%20(data%3A%20any)%20%3D%3E%20T%20%3A%0D%0A%20%20%20%20(data%3A%20any)%20%3D%3E%20data%20is%20T%3B%0D%0Aconst%20isStringBool%20%3D%20%3CValidator4%3E((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22)%3B%0D%0Aconst%20isString%20%3D%20%3CValidator4%3Cstring%3E%3E((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22)%3B%0D%0Aconst%20eventuallyValidate%20%3D%20%3CValidator4%3CPromise%3Cstring%3E%3E%3E%0D%0A%20%20%20%20((data%3A%20any)%20%3D%3E%20typeof%20data%20%3D%3D%3D%20%22string%22%20%3F%20Promise.resolve(data)%20%3A%20Promise.reject())%0D%0A%0D%0A%0D%0Afunction%20useTypeGuard(data%3A%20unknown)%3A%20string%20%7C%20undefined%20%7B%0D%0A%20%20%20%20if%20(isString(data))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20data%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20useBoolean(data%3A%20any)%3A%20string%20%7C%20undefined%20%7B%0D%0A%20%20%20%20if%20(isStringBool(data))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20data%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20usePromise(data%3A%20unknown)%20%7B%0D%0A%20%20%20%20return%20eventuallyValidate(data)%0D%0A%20%20%20%20%20%20%20%20.then(d%20%3D%3E%20console.log(%22valid%22%2C%20d))%0D%0A%20%20%20%20%20%20%20%20.catch(()%20%3D%3E%20console.warn(%22invalid%22))%0D%0A%7D) where I noodled around on some things. I did manage to get something kinda working with a combination of a default generic parameter and conditional types, but it's kind of complicated and may not be what we want at the end of the day.

Here's the final form of that experiment:

```ts
type Validator4<T=void> =
    T extends void ? (data: any) => boolean :
    T extends Promise<any> ? (data: any) => T :
    (data: any) => data is T;

// Example guard functions
const isStringBool = <Validator4>((data: any) => typeof data === "string");
const isString = <Validator4<string>>((data: any) => typeof data === "string");
const eventuallyValidate = <Validator4<Promise<string>>>
    ((data: any) => typeof data === "string" ? Promise.resolve(data) : Promise.reject())
```

Something like this _might_ work for `ValidateFunction`, but in trying to figure out how to get it to check, I may have strayed a bit from how people actually use AJV.

A simpler interface would probably be easier to type check, so I might be leaning toward a smaller wrapper for TypeScript users with fewer union return types, either as an alternate interface or maybe a separate package.

But either way, having the compiled code generate an annotation (so that it could be more easily imported) would probably be a good idea (although that's probably a different ticket).

**Comment by heartistizio** [comment]
What's the status of this issue? I'm adding my own issue description below:

**What version of Ajv you are you using?**
5.5.2

**What problem do you want to solve?**
Currently `ajv` types for `ValidateFunction.schema` is `object | boolean`, which is a really weird type.

**What do you think is the correct solution to problem?**
I propose we add a generic type to `compile` and `compileAsync`. If possible and there's nothing against it's possible to remove all the `object` occurances.

**Will you be able to implement it?**
I've created a possible solution snippet, of course seeing as you are more familiar you'll be able to catch my mistakes.

```diff
diff --git a/lib/ajv.d.ts b/lib/ajv.d.ts
index 5e7cfa7..845dcb0 100644
--- a/lib/ajv.d.ts
+++ b/lib/ajv.d.ts
@@ -45,7 +45,7 @@ declare namespace ajv {
     * @param  {object|Boolean} schema schema object
     * @return {Function} validating function
     */
-    compile(schema: object | boolean): ValidateFunction;
+    compile<T>(schema: T): ValidateFunction<T>;
     /**
     * Creates validating function for passed schema with asynchronous loading of missing schemas.
     * `loadSchema` option should be a function that accepts schema uri and node-style callback.
@@ -55,7 +55,7 @@ declare namespace ajv {
     * @param {Function} callback optional node-style callback, it is always called with 2 parameters: error (or null) and validating function.
     * @return {PromiseLike<ValidateFunction>} validating function
     */
-    compileAsync(schema: object | boolean, meta?: Boolean, callback?: (err: Error, validate: ValidateFunction) => any): PromiseLike<ValidateFunction>;
+    compileAsync<T>(schema: T, meta?: Boolean, callback?: (err: Error, validate: ValidateFunction) => any): PromiseLike<ValidateFunction<T>>;
     /**
     * Adds schema to the instance.
     * @param {object|Array} schema schema or array of schemas. If array is passed, `key` and other parameters will be ignored.
@@ -145,7 +145,7 @@ declare namespace ajv {
     error(...args: any[]): any;
   }
 
-  interface ValidateFunction {
+  interface ValidateFunction<T = boolean> {
     (
       data: any,
       dataPath?: string,
@@ -153,7 +153,7 @@ declare namespace ajv {
       parentDataProperty?: string | number,
       rootData?: object | Array<any>
     ): boolean | PromiseLike<any>;
-    schema?: object | boolean;
+    schema?: T;
     errors?: null | Array<ErrorObject>;
     refs?: object;
     refVal?: Array<any>;
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
```

**Comment by ostrowr** [comment]
I've been working on https://github.com/ostrowr/ts-json-validator the last couple days, which does pretty much exactly this, and happens to use ajv behind the scenes anyway. If a maintainer would be interested, I'm happy to port a bunch of that work over to ajv, or implement a plugin that implements these types.

**Comment by cogell** [comment]
@ostrowr your library looks great and the clear, concise documentation is refreshing. thank you thank you thank you. (now to give it a try...)

**Comment by epoberezkin** [comment]
@ostrowr implementing plugin is better as Ajv is not a typescript library.

**Comment by Janpot** [comment]
@ostrowr Do you think it is possible to implement this functionality, solely by updating [the types](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts)? Or does it depend on updates to the Ajv runtime as well?

**Comment by ostrowr** [comment]
> @ostrowr Do you think it is possible to implement this functionality, solely by updating [the types](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts)? Or does it depend on updates to the Ajv runtime as well?

@Janpot Unfortunately, as it currently stands it would probably require some changes to the runtime, since each sub-schema (currently) needs to be marked using "createSchema."

**Comment by sinclairzx81** [comment]
This library may be of interest https://github.com/sinclairzx81/typebox

**Comment by epoberezkin** [comment]
@dcolthorp mere 2 years later consider to include it in upcoming v7 release :)

**Comment by epoberezkin** [comment]
@ostrowr now would be the great time to get some of the ideas from ts-json-validator into ajv - it's now re-written into typescript (v7-alpha branch). I plan to release v7 beta end of September, it would be great if you could have a look. Thank you.

**Comment by epoberezkin** [comment]
I've never seen that many thumbs-up on a single issue in Ajv - thanks a lot for supporting this feature!

Validating type guards are now in v7-alpha branch, coming to npm soon.

I've also added `JSONSchemaType<T>` - a utility type that for a given data interface recursively constructs the type for JSON Schema for this data - it supports records, dictionaries, arrays and tuples (of any depth).

So if you write JSON schemas manually rather than generate them from interfaces, e.g. when typescript interface is not expressive enough to define dependencies or when you want to add any additional restrictions on top of the interface, this type could simplify it and help avoiding mistakes and ensuring correctness of the schema.

Check it out here:

type: https://github.com/ajv-validator/ajv/blob/v7-alpha/lib/types/json-schema.ts
tests with the usage example: https://github.com/ajv-validator/ajv/blob/v7-alpha/spec/types/json-schema.spec.ts

Any feedback or suggestions would be really appreciated :)

**Comment by ostrowr** [comment]
> @ostrowr now would be the great time to get some of the ideas from ts-json-validator into ajv - it's now re-written into typescript (v7-alpha branch). I plan to release v7 beta end of September, it would be great if you could have a look. Thank you.

I probably won't have time to make any serious contributions before the end of September, but I'll certainly take a look and see where I can help ASAP!
