### ISSUE TITLE
Missing module property in package.json

### ISSUE THREAD

**Issue by rolandjitsu** [ajv-validator/ajv#758]
**The version of Ajv you are using**
6.4.0

**The environment you have the problem with.**
Browser

**Your code (please make it as small as possible to reproduce the issue).**
Not a code problem.

The problem occurs when I try to minify my app assets in a reactjs env. The issue is described at [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).

There is a simple fix for it though. Just add the `module` property in `package.json`, alongside `main`, that points to `"dist/ajv.min.js"`.

Ideally, the `main` should point to the CommonJS dist file for nodejs compatibility (as the other party also suggests).

I can make a PR if needed.

**If your issue is in the browser, please list the other packages loaded in the page in the order they are loaded. Please check if the issue gets resolved (or results change) if you move Ajv bundle closer to the top.**

**Results in node.js v4.**

**Results and error messages in your platform.**

**Comment by epoberezkin** [comment]
> The problem occurs when I try to minify my app assets in a reactjs env. The issue is described at create-react-app.

That is some other issue, as this package only uses ES5 - there is no ES6 code here. 

Also please describe the actual problem.

**Comment by rolandjitsu** [comment]
@epoberezkin the issue is described in the create-react-app readme I referenced, the error is just a simple message.

It started happening after I added this lib as dep, so I investigated and figured out that adding the module property to this lib's package.json fixes it (as the create-react-app suggested it would).

After digging deeper, I discovered it is caused by the [uri-js](https://github.com/garycourt/uri-js) dependency that this lib has ([lib/compile/resolve.js#L3](https://github.com/epoberezkin/ajv/blob/309f9e38b9da0373b67135fc2400f08f5ade28b7/lib/compile/resolve.js#L3)).

For some reason, create-react-app uses the esnext from uri-js and it fails.

Adding the module prop to this lib's package.json seemed to have fixed the problem during build, but perhaps I should open an issue on the uri-js side or create-react-app.

**Comment by epoberezkin** [comment]
Please check if the issue happens with 6.3.x - it used core url instead of uri-js. It may require changes in uri-js indeed.

**Comment by rolandjitsu** [comment]
I've just tried it out and the issue doesn't occur if I use `6.3.0`.

It's a bit strange though, because the uri-js's main points to a compatible commonjs source, but for some reason, create-react-app picks up the other source (the esnext).

I'll investigate further and keep you updated.

In any case, it might be a better idea if this package's `main` points to the dist `ajv.bundle.js` instead of the source in `lib` (because the bundle is compatible with both nodejs and common js envs). Or add a `{"browser": "dist/ajv.bundle.js"}` property which points to the bundle.

**Comment by epoberezkin** [comment]
@rolandjitsu I think it maybe an issue in create-react-app, I'd say it's worth reporting to them. Looks like they may be not picking it correctly from sub-dependencies.

I am not certain whether exposing build artefacts via package.json is the correct solution, some other opinions on the issue could be helpful here. To me it seems that the place for them is your app config (or html head) and you should not be using them as part of build process, only if you use them separately.

In this way if you just load ajv.bundle.js as a separate script file in the browser, whether from the package, or from cdnjs, it will "just work", as it exposes globals to be compatible with the most module systems. So you should be able to simply use global Ajv and also use `require('ajv')` in the browser.

If you are including ajv in your bundle it doesn't seem correct to use a bundled file, you should use the file in package.json `main` property. If some build system can't work with it, the issue should be addressed in that build system rather than here.

**Comment by rolandjitsu** [comment]
@epoberezkin Most likely yes, I will create a repo and report it.

I agree with that the main should still point to the source, but adding the `browser` property is actually helpful for build systems that look for a bundle that's compatible in the browser. Check the [specs](https://github.com/defunctzombie/package-browser-field-spec) for it.

**Comment by one19** [comment]
Just to chime in: we're using `ajv` in very standard webpacked and babeled environment.  The `uri-js` version used ends up importing with argument spread. It's a bit wild that the only module we need to include in transpilation is `uri-js` because of `ajv` and its incompatibility with ie11. Is anyone looking at this issue at the moment?

`uri-js` has 2 open issues at the moment, both pertaining to this, but they haven't budged either in the 24 days the issue has been open.

Just wanted to chime in, and say that this isn't just a `create-react-app` issue, it's a bit more widespread for anyone wanting interop with ie11

**Comment by HenrikGr** [comment]
I started to use ajv last weekend in my create-react-app projects and stumbled on this as well. create-react-app can not minify uri-js.

I'm using version 6.5 of ajv.

Would be nice if this could be solved.

**Comment by Steffan-Ennis** [comment]
I would like this fixed too. I have to include `/node_modules\/uri-js/` in my webpack javascript rule when consuming this library.

**Comment by Punji** [comment]
Gary just released uri-js@^4.2.2 to fix this issue:
[https://github.com/garycourt/uri-js/issues/24](url)

Can you please update Ajv to use it?

**Comment by epoberezkin** [comment]
Ajv will pick it up, no update is necessary - `npm update` should fix it for you (or reinstall)

**Comment by Punji** [comment]
Thanks for the tip @epoberezkin, Ajv is working fine with create-react-app now!
