### ISSUE TITLE
Should not include `ajv-i18n` as a peer dependency

### ISSUE THREAD

**Issue by blakeembrey** [ajv-validator/ajv#78]
Just a consideration, but `ajv-i18n` is a peer dependency even though it's not used during runtime. This results in warnings for the user, even when we don't want to use it. It's a little confusing. Maybe just link to it, but don't actually list it as a dependency?

**Comment by epoberezkin** [comment]
Yes, I thought about it. The problem is version compatibility... ajv 1.4 needs ajv-i18n 0.1 and ajv 2.0 needs ajv-i18n 1.0.
Is there a better way to enforce it than peer dependencies?
Starting from npm version 3 peer dependencies are optional - they are not installed, so I thought this forced installation issue will go away...

**Comment by blakeembrey** [comment]
It's not so much a forced installation (I'm catering from v0.10 - v5 anyway), but it'll warn or even show a big red box on installation saying invalid peer dependency because none was installed. I don't think there's a perfect solution in `package.json`, because these are for dependencies (not hypothetical dependencies). I would recommend just a nice, clear warning on the README here and/or `ajv-i18n`.

**Comment by blakeembrey** [comment]
@epoberezkin And, actually, you always have the peer dependency in `ajv-i18n`. No need for it here, and that'll fix the error. Still recommend including a notice in the docs though.

**Comment by epoberezkin** [comment]
I will remove then - I also didn't like this red box... You are right that peer dependency in one place is enough.
