### ISSUE TITLE
id, $id, confusion in general, and since ajv 4 in particular

### ISSUE THREAD

**Issue by gregglind** [ajv-validator/ajv#793]
This is a less an ajv specific and more a "Ids/refs are confusing in Json-schema".  

Maybe documentation / example request for something with both internal ids and how to do that under current (6.5.0) ajv?  

As always, Ajv is great, and I am glad you are interpreting / understanding the spec so I don't have to!

**Comment by epoberezkin** [comment]
@gregglind have you seen this: https://github.com/epoberezkin/ajv#ref?

I was thinking to make a separate document on $refs (REFS.md:) but never came around to it. PR is welcome.

**Comment by gregglind** [comment]
I have!  I appreciate you taking the time to explain it.  

I use the 'schemas' key for instantiation in some projects. Refs within the *same* file are *also* confusing.  I realize this is an obscure / advanced use case.  

Perhaps I need to look at how one of the 'deref' packages works, and write it out!

**Comment by epoberezkin** [comment]
Just bear in mind that $ref in JSON schema does not mean de-referencing, it it not the same as copy pasting the referenced schema instead of $ref in general case. There was a long conversation on JSON schema org on the subject and also see https://github.com/epoberezkin/ajv/blob/master/FAQ.md#generating-schemas-with-resolved-references-ref

**Comment by epoberezkin** [comment]
The closest programming analogy to $ref is a function call (and that's how ajv implements it internally - only the simplest cases are inlined as an optimisation), not a macro as many people seem to think.
