### ISSUE TITLE
$data 

### ISSUE THREAD

**Issue by atomictag** [ajv-validator/ajv#845]
This is not really an issue, because it works, but I am not sure why it does.
I want to make a property within an object `personalDetails.occupation` required if the data does not contain a certain top-level object (`payor`). I tried a few options without much success and then I fiddled with $data and came out with the solution below. If works as I expect, but I am not sure it is really correct (or may have side-effects) because i can't really make sense of what's going on.
Thanks for your help!

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

6.5.3

**Ajv options object**

```javascript
const ajv = new Ajv({
    $data: true,
    allErrors: true,
    jsonPointers: true,
    format : "full",
    useDefaults : true,
    removeAdditional : true});
// using ajv-errors
require('ajv-errors')(ajv, { keepErrors: false, singleError : false });
```

**JSON Schema**

```json
{
    "$schema": "http://json-schema.org/schema#",
    "$id": "https://example.com/schemas/ztest.schema.json",
    "type": "object",
    "properties": {
        "personalDetails": {
            "allOf" : [
                {
                    "if" : { "required" : { "$data": "/payor" }},
                    "then" : { "required": ["occupation"] }
                }
            ]
        },
        "payor" : {
            "type" : "object"
        }
    }
}
```
Please note the use of the $data pointer within the `if` condition.
Perhaps counter-intuitively, when `payor` is not specified the condition becomes true and therefore `occupation` becomes required. Conversely, when `payor` is defined the condition is never true. 

**Sample data**

This validates because no `occupation` is required if a `payor` is defined
```json
{
  "personalDetails" : {},
  "payor" : {}
}
```

This also validates because `occupation` is defined when `payor` is not defined
```json
{
  "personalDetails" : { "occupation" : "butcher" }
}
```

This (correctly) fails validation because `payor` is not defined
```json
{
  "personalDetails" : { }
}
```

**What results did you expect?**

The behaviour is correct. However I am not sure this is happening by chance or if the schema above is correct, given the counter-intuitive condition.

**Comment by epoberezkin** [comment]
The way it works:

1. when property payor is present, `"required" : { "$data": "/payor" }` fails because the value of payor is not an array, and the required keyword should be array. So "then" schema is never validated and the validation passes.
2. when property payor is absent, `"required" : { "$data": "/payor" }` passes because the value of payor is considered undefined, so it's the same as not having `required` at all. So "then" schema is validated and "occupation" is required.

The logic you want can be achieved with a couple of compound keywords (allOf etc.) or with if/then/else (draft-07), you don't need run-time schema substitution with $data at all. Please submit the question to StackOverflow - it's a general JSON schema usage question.

**Comment by atomictag** [comment]
many thanks I soon realized it was not a great solution - and definitely not an issue of this awesome lib!
thank you for taking the time to look at this and keep up with the great job

**Comment by epoberezkin** [comment]
see https://runkit.com/esp/5b7d5de4b6b3d700123c8d66 to understand how it works
