### ISSUE TITLE
Allow adding extra definitions

### ISSUE THREAD

**Issue by fgarcia** [ajv-validator/ajv#947]
**What version of Ajv you are you using?**
6.9.1

**What problem do you want to solve?**

I want to extend/update my schema definitions. For example, my code has a central service where I initialize my Ajv compiler like this:

      let extra = {
        $id: 'http://example.com/schemas/core',
        definitions: {
          domainTask: {...},
        },
      }
      var ajv = new Ajv({ schemas: [extra] })

I keep that instance of Ajv to solve the definition references in all my schemas

          items: { $ref: 'core#/definitions/domainTask' },

The problem now is that I cannot extend my original list of definitions for `http://example.com/schemas/core`. If I try to add new ones it will fail because the $id is already taken.

Currently it seems that I am forced to load all my definitions at once if I want to use references. The only exception would be switching to async validation, but that levels up the complexity of my deployment (to serve the schemas).

**What do you think is the correct solution to problem?**

A way to add new definitions to an existing schema. Like ajv.getSchema(...).addDefinitions()

**Will you be able to implement it?**
no :(

**Comment by fgarcia** [comment]
After writing my question I realized that actually I can modify existing schemas, but i am  not sure if this can have side effects. Here goes my example:

https://gist.github.com/fgarcia/081a77518f33747fa61612a124c82d0b

**Comment by epoberezkin** [comment]
@fgarcia your approach of modifying schema via the reference should work, surprisingly, but it is a hack that I would avoid using - it will be very difficult to reason about and to debug.
There is no penalty for having each definition in a separate file and adding them to Ajv instance all at once or as needed - they are only compiled on demand, lazily, even if you add them all at once.
So instead of addressing them via JSON pointer after #, you would be simply addressing them by different schema $id’s, e.g. https://example.com/defs/myDefinition (and $id structure may match folders structure to make it easier to reason about or be downloadable via http, but the spec has no such requirement - how you map $ids to actual schemas is completely up to you). A common approach is to group related definitions across multiple files.
Btw, I do not understand the use case of extending definitions during run time? Why cannot they all be pre-added to Ajv instance during application bootstrapping? Do you generate them dynamically?

**Comment by fgarcia** [comment]
I was concerned with the weight/cost of loading my app, specially in the browser.

There is still a lot I have to learn about how to use schemas in my code. I still have problems dealing with the verbosity of using schemas.

Right now my objective is understanding better how to deal with the verbosity (which I see is totally justified). Since I wrote my post I realized that I need some type of factory/service object to manage some patterns in the definition of my schemas.

Thanks for long answer, now I've got something to chew around this concept. Looks like it will be a coordination of SchemaFactory, SchemaService and AppPartsLoadingService.
