### ISSUE TITLE
Request to make console optional for default construction

### ISSUE THREAD

**Issue by shamasis** [ajv-validator/ajv#950]
**The version of Ajv you are using**
latest

**The environment you have the problem with**
NodeJS vm.js

**Your code (please make it as small as possible to reproduce the issue)**
```
var Ajv = require('ajv'),
    ajv = new Ajv(); // note {logger: console} not provided
```

**Issue**
Ajv assumes console to be present in the environment. It is an acceptable for all normal use cases. But we use AJV within Node VM module and that is sandboxed to not have console.

The following line https://github.com/epoberezkin/ajv/blob/master/lib/ajv.js#L488 assumes console to be present. This results in issues such as https://github.com/postmanlabs/postman-app-support/issues/3199 and requires to have a longer boilerplate code.

If it is okay, we can send a PR that checks if console is absent even in global scope and injects a stub.

**Comment by epoberezkin** [comment]
I am not convinced that making Ajv resilient to the absence of global console is the right approach, given that
1) 2 main JS environments have it (and probably most main environments have it)
2) there are simple solutions that don’t require library changes:
  a) pass console object to Ajv instance - there is an option
  b) define global console if for whatever reason you cannot pass it (in case you don’t control instance options).

Why does it have to fixed in the library?

**Comment by epoberezkin** [comment]
Having thought about it, I believe that even for the environments that do not have "console" object, I believe it is better to fail, to make users aware that the library does not log in cases it is supposed to, rather than to do nothing silently.

Once users understand that either the global console or "logger" option is required, they will have a choice to either supply another way to log or to supply a logger that does nothing.

**Comment by shamasis** [comment]
@epoberezkin - I am with you on the thought process. Maybe as a work around this could be a module level setting. Say...
```
var Ajv = require('ajv');
Ajv.debug({
    console: specialConsoleFunctionForAllSubsequentConstruction
});
```

AJV is now getting distributed to 7+ million users via Postman Sandbox and I really want to make it easier (not quirky) for them. If you think the above idea is good then someone from our team would be glad to send a PR.

**Comment by epoberezkin** [comment]
@shamasis - how do they log? Why there is no console object?

So you suggest to provide a constructor api to provide default options for future instances?

If so, something like Ajv.options() probably makes more sense. Need to think about it.

**Comment by igorpupkinable** [comment]
@epoberezkin logger setter would help a lot since logger instance is constructed on every invocation in some cases/environments.
An example would be Azure Functions where [context](https://learn.microsoft.com/en-us/javascript/api/@azure/functions/invocationcontext?view=azure-node-latest#methods) which acts as a logger is unavailable before endpoint is called.
```ts
import { app } from '@azure/functions';
import { Ajv } from 'ajv/dist/jtd.js';

const ajv = new Ajv({ logger: ??? }); // Ideally this should be constructed once on module load.
const handler = async function (request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
  // context is constructed on every invocation
  ajv.setLogger(context); // ???
  ...
}

app.post('example', { handler }); // Register function at /api/example endpoint for POST
```
